### ISSUE TITLE
ece2cmor3 fails when processing IFS ouptut from the first year

### ISSUE THREAD

**Issue by klauswyser** [EC-Earth/ece2cmor3#172]
When trying to process the first year of IFS output (i.e. the files in <my_exp>/output/ifs/001 directory) ece2cmor3 stops with:
````
INFO:ece2cmor3.taskloader:Found 349 cmor target variables in input variable list.
ERROR:ece2cmor3.taskloader:Could not find parameter table entry for rsdsdiff in table 3hr...skipping variable. This variable is ignored
[...more ERROR lines from taskloader that probably can be ignored...]
INFO:ece2cmor3.taskloader:Created 130 ece2cmor tasks from input variable list.
INFO:ece2cmor3.ece2cmorlib:Selected 130 IFS tasks from 130 input tasks
Traceback (most recent call last):
  File "./ece2cmor.py", line 97, in <module>
    main()
  File "./ece2cmor.py", line 89, in main
    maxsizegb=args.tmpsize)
  File "/home/sm_wyser/.conda/envs/ece2cmor3-3-2/lib/python2.7/site-packages/ece2cmor3-1.0.0-py2.7.egg/ece2cmor3/ece2cmorlib.py", line 159, in perform_ifs_tasks
    outputfreq=ofreq, tempdir=tempdir, maxsizegb=maxsizegb, autofilter=auto_filter)):
  File "/home/sm_wyser/.conda/envs/ece2cmor3-3-2/lib/python2.7/site-packages/ece2cmor3-1.0.0-py2.7.egg/ece2cmor3/ifs2cmor.py", line 72, in initialize
    datafiles = select_files(path, exp_name_, start, length)
  File "/home/sm_wyser/.conda/envs/ece2cmor3-3-2/lib/python2.7/site-packages/ece2cmor3-1.0.0-py2.7.egg/ece2cmor3/ifs2cmor.py", line 688, in select_files
    (end_date > cmor_utils.get_ifs_date(f) >= start_date)]
  File "/home/sm_wyser/.conda/envs/ece2cmor3-3-2/lib/python2.7/site-packages/ece2cmor3-1.0.0-py2.7.egg/ece2cmor3/cmor_utils.py", line 117, in get_ifs_date
    return datetime.datetime.strptime(ss, "%Y%m").date()
  File "/home/sm_wyser/.conda/envs/ece2cmor3-3-2/lib/python2.7/_strptime.py", line 332, in _strptime
    (data_string, format))
ValueError: time data '000000' does not match format '%Y%m'
````
Maybe it doesn't work for the first month because there is no previous month file, but I also get the very same error when setting the date to 1990-02-01

**Comment by klauswyser** [comment]
I created an output/ifs/000 directory and moved the ICM*000000 files there, is that what you mean with "one directory up"? For later years I noticed that ece2cmor3 looks in directory $(leg-1) when processing teh first month.

I haven't tested yet your latest commit, will do next week.

**Comment by klauswyser** [comment]
Moving the ICM*000000 files from 001/ ro 000/ helps somewhat, I can now process all months from Feb to Dec. But when trying to process January in the 001/ directory I still get troubles:
````
INFO:ece2cmor3.grib_filter:Searching for previous month file of /nobackup/rossby20/rossby/joint_exp/ecearth/sm_wyser/ece-run/tc04/output/ifs/001/ICMGGtc04+199001
INFO:ece2cmor3.grib_filter:No regular previous month files found, taking initial state files...
````
So far so good, but then
````
ERROR:ece2cmor3.cdoapi:(returncode:1) cdo showltype: Started child process "selcode,129 /scratch/local/199001/129.128.210.6 (pipe1.1)".
Warning (cgribexScanTimestep2): Record 16 (id=129.128 lev1=60000 lev2=0) timestep 2: Parameter not defined at timestep 1!
cdo(2) selcode: Open failed on >/scratch/local/199001/129.128.210.6<
Unsupported file structure
````
and so on.

Maybe I should rename ``000/ICMGG+000000`` to ``000/ICMGG+198912``?

**Comment by goord** [comment]
Should be fixed after rev. 5f4490ac441c49dd3cf4c0c342842791218d55c8
