### ISSUE TITLE
ece2cmor3 problem with posixpath

### ISSUE THREAD

**Issue by klauswyser** [EC-Earth/ece2cmor3#182]
I tried using ece2cmor3 on a different platform (Linux, x86_64). Installation under Anaconda 5.0.1 went smoothly, no problem. But when trying to run ``ece2cmor.py`` I get:
````
Traceback (most recent call last):
  File "./ece2cmor.py", line 101, in <module>
    main()
  File "./ece2cmor.py", line 91, in main
    maxsizegb=args.tmpsize)
  File "/cfs/klemming/nobackup/w/wyser/anaconda-ece2cmor3/lib/python2.7/site-packages/ece2cmor3-1.0.0-py2.7.egg/ece2cmor3/ece2cmorlib.py", line 159, in perform_ifs_tasks
    outputfreq=ofreq, tempdir=tempdir, maxsizegb=maxsizegb, autofilter=auto_filter)):
  File "/cfs/klemming/nobackup/w/wyser/anaconda-ece2cmor3/lib/python2.7/site-packages/ece2cmor3-1.0.0-py2.7.egg/ece2cmor3/ifs2cmor.py", line 99, in initialize
    grib_filter.initialize(ifs_gridpoint_file_, ifs_spectral_file_, temp_dir_)
  File "/cfs/klemming/nobackup/w/wyser/anaconda-ece2cmor3/lib/python2.7/site-packages/ece2cmor3-1.0.0-py2.7.egg/ece2cmor3/grib_filter.py", line 48, in initialize
    prev_gridpoint_file, prev_spectral_file = get_prev_files(gridpoint_file)
  File "/cfs/klemming/nobackup/w/wyser/anaconda-ece2cmor3/lib/python2.7/site-packages/ece2cmor3-1.0.0-py2.7.egg/ece2cmor3/grib_filter.py", line 144, in get_prev_files
    date = cmor_utils.get_ifs_date(gpfile)
  File "/cfs/klemming/nobackup/w/wyser/anaconda-ece2cmor3/lib/python2.7/site-packages/ece2cmor3-1.0.0-py2.7.egg/ece2cmor3/cmor_utils.py", line 110, in get_ifs_date
    fname = os.path.basename(filepath)
  File "/cfs/klemming/nobackup/w/wyser/anaconda-ece2cmor3/lib/python2.7/posixpath.py", line 114, in basename
    i = p.rfind('/') + 1
AttributeError: 'NoneType' object has no attribute 'rfind'
````
Any idea?

**Comment by goord** [comment]
Hi Klaus, I get the same error when I type 
```
print os.path.basename(None)
```
on my system, so I suspect the input of the function is ```None```, which  may be caused by an earlier error

**Comment by klauswyser** [comment]
Pretty strange, I tried again the same command as yesterday and today everything just works fine. Maybe there was something strange in my env yesterday because I created the Anaconda environment twice.
