### ISSUE TITLE
could not load xarray

### ISSUE THREAD

**Issue by klauswyser** [EC-Earth/ece2cmor3#204]
I just checked out and fresh copy of ece2cmor3 and installed everything from scratch (in Anaconda). When trying to run ece2cmor it stops with:
````
Could not load xarray
INFO:ece2cmor3.cmor_target:CMOR tables data_specs_version : 01.00.24
INFO:ece2cmor3.cmor_target:CMOR tables cmor_version : 3.3
INFO:ece2cmor3.cmor_target:CMOR tables Conventions : CF-1.7 CMIP-6.2
INFO:ece2cmor3.cmor_target:CMOR tables table_date : 13 June 2018
Traceback (most recent call last):
  File "./ece2cmor.py", line 111, in <module>
    main()
  File "./ece2cmor.py", line 89, in main
    taskloader.load_targets(args.vars, model_active_flags)
  File "/home/sm_wyser/.conda/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-1.0.0-py2.7.egg/ece2cmor3/taskloader.py", line 53, in load_targets
    targetlist = load_targets_json(varlist)
  File "/home/sm_wyser/.conda/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-1.0.0-py2.7.egg/ece2cmor3/taskloader.py", line 77, in load_targets_json
    varlist = json.loads(vartext)
  File "/home/sm_wyser/.conda/envs/ece2cmor3/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/home/sm_wyser/.conda/envs/ece2cmor3/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/sm_wyser/.conda/envs/ece2cmor3/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 107 column 6 (char 1708)
````
This example is for processing ocean output, but I get the very same error when trying to process atmospheric variables.

Is it the missing xarray package, or something else?

**Comment by treerink** [comment]
Do the  `nosetests` in the basic dir run fine on your machine?

**Comment by klauswyser** [comment]
I don't get the "xarray" message with ``cdo -V``. And ``nosetests`` is not giving valuable information:
````
(ece2cmor3) [sm_wyser@triolith1 ece2cmor3]$ nosetests

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
````

**Comment by klauswyser** [comment]
Sorry, I just realised that I did run nosetest in the wrong directory. When doing it in the correct place it works fine, I get a couple of warnings from the CMOR library, that's it.

**Comment by klauswyser** [comment]
It was a superfluos semicolon in my varlist json file. Sorry for the trouble.
