### ISSUE TITLE
Error with user-defined parameter table 

### ISSUE THREAD

**Issue by oloapinivad** [EC-Earth/ece2cmor3#207]
Hi all,

Trying to cmorize NEMO data with a user-defined parameter table with the flag `--nemopar` I am getting this error: 

````
Traceback (most recent call last):
  File "/marconi_work/IscrC_C2HEClim/ecearth3/cmorization/ece2cmor3/ece2cmor3/ece2cmor.py", line 111, in <module>
    main()
  File "/marconi_work/IscrC_C2HEClim/ecearth3/cmorization/ece2cmor3/ece2cmor3/ece2cmor.py", line 89, in main
    taskloader.load_targets(args.vars, model_active_flags)
  File "/marconi/home/userexternal/pdavini0/work/opt/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-1.0.0-py2.7.egg/ece2cmor3/taskloader.py", line 71, in load_targets
    return create_tasks(targetlist, active_components, silent)
  File "/marconi/home/userexternal/pdavini0/work/opt/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-1.0.0-py2.7.egg/ece2cmor3/taskloader.py", line 279, in create_tasks
    target.variable, target.table, components.models[modelmatch]["parfile"]))
KeyError: 'parfile'
````

This is not occurring if I use the default nemo parameter table. 

Cheers,
Paolo

**Comment by goord** [comment]
Hi Paolo, can you test your issue once more after pulling and re-installing? Thx

**Comment by oloapinivad** [comment]
Yes it works now. It stops immediately for an issue with the parameter table I supply, but the original problem seems to be solved.

FYI, this is the problem with the parameter table from PRIMAVERA

`````
^[[1;31;47m!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: You are defining variable 'masso' (table Omon)  with 2 dimensions, when it should have 1
!
!!!!!!!!!!!!!!!!!!!!!!!!!^[[0m

Traceback (most recent call last):
  File "/marconi_work/IscrC_C2HEClim/ecearth3/cmorization/ece2cmor3/ece2cmor3/ece2cmor.py", line 111, in <module>
    main()
  File "/marconi_work/IscrC_C2HEClim/ecearth3/cmorization/ece2cmor3/ece2cmor3/ece2cmor.py", line 103, in main
    ece2cmorlib.perform_nemo_tasks(args.datadir, args.exp, startdate, length)
  File "/marconi/home/userexternal/pdavini0/work/opt/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-1.0.0-py2.7.egg/ece2cmor3/ece2cmorlib.py", line 177, in perform_nemo_tasks
    nemo2cmor.execute(nemo_tasks)
  File "/marconi/home/userexternal/pdavini0/work/opt/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-1.0.0-py2.7.egg/ece2cmor3/nemo2cmor.py", line 89, in execute
    execute_netcdf_task(dataset, task)
  File "/marconi/home/userexternal/pdavini0/work/opt/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-1.0.0-py2.7.egg/ece2cmor3/nemo2cmor.py", line 128, in execute_netcdf_task
    varid = create_cmor_variable(task, dataset, axes)
  File "/marconi/home/userexternal/pdavini0/work/opt/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-1.0.0-py2.7.egg/ece2cmor3/nemo2cmor.py", line 172, in create_cmor_variable
    original_name=str(srcvar))
  File "/marconi/home/userexternal/pdavini0/work/opt/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/cmor/pywrapper.py", line 536, in variable
    missing_value, tolerance, positive, original_name, history, comment)
_cmor.CMORError: Problem with 'cmor.variable'. Please check the logfile (if defined).
`````

**Comment by oloapinivad** [comment]
These are PRIMAVERA output, from the Stream2 cluster 1 control run I was
mentioning.
The masso variable is in the scalar file.
Cheers,
P

Il giorno mer 8 ago 2018 alle ore 11:23 Gijs van den Oord <
notifications@github.com> ha scritto:

**Comment by oloapinivad** [comment]
Since this is solved, and the relate issue seems a problem with Jon Seddon's PRIMAVERA table, I move this to #162
