### ISSUE TITLE
Cmorization error with CMIP6 1point files

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#261]
I get an cmorization error with the file `t137_1m_19900101_19900228_opa_grid_1point.nc`. The error:

`````
NFO:ece2cmor3.nemo2cmor:Creating NEMO grids in CMOR...
Traceback (most recent call last):
  File "/usr/people/reerink/anaconda2/envs/ece2cmor3/bin/ece2cmor", line 11, in <module>
    load_entry_point('ece2cmor3==1.0.0', 'console_scripts', 'ece2cmor')()
  File "/usr/people/reerink/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-1.0.0-py2.7.egg/ece2cmor3/ece2cmor.py", line 104, in main
    ece2cmorlib.perform_nemo_tasks(args.datadir, args.exp, startdate, length)
  File "/usr/people/reerink/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-1.0.0-py2.7.egg/ece2cmor3/ece2cmorlib.py", line 176, in perform_nemo_tasks
    nemo2cmor.execute(nemo_tasks)
  File "/usr/people/reerink/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-1.0.0-py2.7.egg/ece2cmor3/nemo2cmor.py", line 67, in execute
    create_grids(tasks)
  File "/usr/people/reerink/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-1.0.0-py2.7.egg/ece2cmor3/nemo2cmor.py", line 331, in create_grids
    grid = read_grid(filename)
  File "/usr/people/reerink/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-1.0.0-py2.7.egg/ece2cmor3/nemo2cmor.py", line 352, in read_grid
    return nemo_grid(name, lons, lats)
  File "/usr/people/reerink/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-1.0.0-py2.7.egg/ece2cmor3/nemo2cmor.py", line 386, in __init__
    if input_lats.shape[1] == 1 and input_lats[-1, 0] == input_lats[-2, 0]:
  File "/usr/people/reerink/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/numpy/ma/core.py", line 3169, in __getitem__
    dout = self.data[indx]
IndexError: index -2 is out of bounds for axis 0 with size 1
`````

**Comment by goord** [comment]
Hi Thomas, can you try to cmorize your 1point variables with the new ```nemopoint``` branch?

**Comment by treerink** [comment]
Hi Gijs, unfortunately same message in nemopoint branch:
`````
IndexError: index -2 is out of bounds for axis 0 with size 1
`````

**Comment by goord** [comment]
Are you sure it's exactly the same backtrace? You did re-install ece2cmor3 right? And which CMOR variable should be produced from these files?

**Comment by treerink** [comment]
Sorry Gijs, I forgot the re-install after the branch switch.

Yes it works fine now!

You merge it in the master? Ready for that?

**Comment by goord** [comment]
Yes, done

**Comment by aearamos** [comment]
Hi, @goord. Sorry to reopen this issue, but I think the last update regarding the 1point variables have affected the msftyz cmorization, since the grid_ptr_W_3basin_3D change along nx but ny is one. After the last updates I got the following error:

"
Traceback (most recent call last):
  File "./ece2cmor.py", line 114, in <module>
    main()
  File "./ece2cmor.py", line 104, in main
    ece2cmorlib.perform_nemo_tasks(args.datadir, args.exp, startdate, length)
  File "/gpfs/scratch/pr1eel00/pr1eel17/a1f5/auto-ecearth3/ece2cmor/ece2cmor3/ece2cmorlib.py", line 176, in perform_nemo_tasks
    nemo2cmor.execute(nemo_tasks)
  File "/gpfs/scratch/pr1eel00/pr1eel17/a1f5/auto-ecearth3/ece2cmor/ece2cmor3/nemo2cmor.py", line 67, in execute
    create_grids(tasks)
  File "/gpfs/scratch/pr1eel00/pr1eel17/a1f5/auto-ecearth3/ece2cmor/ece2cmor3/nemo2cmor.py", line 333, in create_grids
    grid_id = write_grid(grid, task_list[0])
  File "/gpfs/scratch/pr1eel00/pr1eel17/a1f5/auto-ecearth3/ece2cmor/ece2cmor3/nemo2cmor.py", line 371, in write_grid
    cell_bounds=grid.vertex_lats)
  File "/apps/PYTHON/2.7.14/INTEL/lib/python2.7/site-packages/CMOR-3.3.3-py2.7-linux-x86_64.egg/cmor/pywrapper.py", line 403, in axis
    (len(cell_bounds), len(coord_vals)))
Exception: error cell_bounds are 1 long and axes coord_vals are 292 long this is not consistent
"
 
If you want you can use that one file I sent you last week to test the output of mssftyz with the last updates.

Thanks.

**Comment by goord** [comment]
O see a horrible typo...

**Comment by goord** [comment]
Hi @aearamos can you retry after rev. 04cf260641945f803b882c7bd470c0e7bf46e7f2?

**Comment by aearamos** [comment]
> Hi @aearamos can you retry after rev. [04cf260](https://github.com/EC-Earth/ece2cmor3/commit/04cf260641945f803b882c7bd470c0e7bf46e7f2)?

Hi, @goord. Already tested and it's working now. I'm glad it was just a typo!

Thanks!

**Comment by treerink** [comment]
Ok, so closing again.
