### ISSUE TITLE
Segmentation fault with CMIP6 cmorization of hfgeou

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#278]
While cmorizing all NEMO output I encountered a segmentation fault with the variable
`````
 Omon hfgeou
`````
which is "Upward geothermal heat flux at sea floor" and is produced in the file:
`````
 001/t144_1m_19900101_19901231_opa_grid_T_2D.nc
`````
In this file the `hfgeou` field actually looks fine. This netcdf file mainly contains 3D (2D + time)  fields. However, beside four other coordinate 2D fields (`nav_lat`,  `nav_lon`, `time_centered_bounds`, `time_counter_bounds`) the `hfgeou` field is the **only 2D field** without a time axis in this file.

Is this a case which is for some reason not covered, does it expect a time axis and crashes with a segmentation fault?

**Comment by treerink** [comment]
The `hfgeou` variable inherit the **operation="once"** property, like a few others in this block in the `field_def_nemo-opa.xml` file:

`````
      <field_group id="constant_fields"  grid_ref="grid_T_2D"  operation="once" >
         <field id="bathy"       long_name="Sea floor depth below geoid"               standard_name="sea_floor_depth_below_geoid"               unit="m"/>
         <field id="areacello"   long_name="Horizontal area of ocean grid cells"       standard_name="cell_area"                                 unit="m2" />
         <field id="hfgeou"      long_name="Upward geothermal heat flux at sea floor"  standard_name="upward_geothermal_heat_flux_at_sea_floor"  unit="W/m2"/>
         <field id="basins"      long_name="ocean tracer region masks"                 standard_name="ocean_tracer_region_masks"                 unit="none"   />
      </field_group>
`````
This causes the fact that this field is written without a time dimension in the Omon table. Cmor requests a time series here because geothermal heautflux in principle varies over time (but obviously this is not the case in NEMO).

**Comment by goord** [comment]
This is similar to the discussion in #232

**Comment by treerink** [comment]
By the way the full error message was:
`````
~/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/cmor/pywrapper.py:764: UserWarning: Error: your data shape ((362, 292)) does not match the expected variable shape ([292, 362, 0])
Check your variable dimensions before caling cmor_write
  warnings.warn(msg)
Segmentation fault (core dumped)
`````
So indeed this was more verbose.

**Comment by goord** [comment]
Thomas can you re-check with the nemo-ofx-fix branch? This branch should also fix the missing ofx variables...

**Comment by goord** [comment]
Ok, the branch works now.

**Comment by treerink** [comment]
Hi Gijs,

I pull the master and run our example:
`````
python setup.py develop
ece2cmor /net/bhw463/nobackup/users/reerink/cmip6-ec-earth-output/t144/001 1990-01-01 --conf ece2cmor3/resources/metadata-template.json --oce --vars /usr/people/reerink/json-data-requests/varlist-nemo-hfgeou.json --exp t144
`````
But get an error:
`````
C Traceback:
! In function: cmor_variable
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: you did not provide the 'positive' argument for variable: hfgeou (table Omon)
!
!!!!!!!!!!!!!!!!!!!!!!!!!

Traceback (most recent call last):
  File "/usr/people/reerink/anaconda2/envs/ece2cmor3/bin/ece2cmor", line 11, in <module>
    load_entry_point('ece2cmor3', 'console_scripts', 'ece2cmor')()
  File "/usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/ece2cmor.py", line 115, in main
    ece2cmorlib.perform_nemo_tasks(args.datadir, args.exp, startdate, length)
  File "/usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/ece2cmorlib.py", line 176, in perform_nemo_tasks
    nemo2cmor.execute(nemo_tasks)
  File "/usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/nemo2cmor.py", line 92, in execute
    execute_netcdf_task(dataset, task)
  File "/usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/nemo2cmor.py", line 131, in execute_netcdf_task
    varid = create_cmor_variable(task, dataset, axes)
  File "/usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/nemo2cmor.py", line 190, in create_cmor_variable
    original_name=str(srcvar))
  File "/usr/people/reerink/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/cmor/pywrapper.py", line 546, in variable
    missing_value, tolerance, positive, original_name, history, comment)
_cmor.CMORError: Problem with 'cmor.variable'. Please check the logfile (if defined).
`````

**Comment by goord** [comment]
Oops sorry, I was too confident there, can you try once more with the master?

**Comment by goord** [comment]
Sorry, my fix was not compatible with the fixes for global variables (which is rather hacky), can you update and try again?

**Comment by treerink** [comment]
Yes this issue seems solved now. Thanks!

A nex error is reported in #280.

So closing this one.
