### ISSUE TITLE
AttributeError with CMIP6 cmorization

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#280]
`````
Traceback (most recent call last):
  File "/usr/people/reerink/anaconda2/envs/ece2cmor3/bin/ece2cmor", line 11, in <module>
    load_entry_point('ece2cmor3', 'console_scripts', 'ece2cmor')()
  File "/usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/ece2cmor.py", line 115, in main
    ece2cmorlib.perform_nemo_tasks(args.datadir, args.exp, startdate, length)
  File "/usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/ece2cmorlib.py", line 176, in perform_nemo_tasks
    nemo2cmor.execute(nemo_tasks)
  File "/usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/nemo2cmor.py", line 87, in execute
    create_depth_axes(dataset, task_list, table)
  File "/usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/nemo2cmor.py", line 212, in create_depth_axes
    depth_bounds = ds.variables[getattr(depth_coordinates, "bounds")]
  File "netCDF4/_netCDF4.pyx", line 4057, in netCDF4._netCDF4.Variable.__getattr__
  File "netCDF4/_netCDF4.pyx", line 3868, in netCDF4._netCDF4.Variable.getncattr
  File "netCDF4/_netCDF4.pyx", line 1289, in netCDF4._netCDF4._get_att
  File "netCDF4/_netCDF4.pyx", line 1745, in netCDF4._netCDF4._ensure_nc_success
AttributeError: NetCDF: Attribute not found
`````

**Comment by treerink** [comment]
Solved in the meanwhile
