### ISSUE TITLE
Error in cmorizing Omon vo: Could not find all axes for this variable. 

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#287]
Hi Gijs,

Unfortunately tt seems some fixes of yesterday cause troubles which were not there before. I now have the error (not before when I cmorized the same stuff):
`````
INFO:ece2cmor3.nemo2cmor:Cmorizing NEMO tasks...
INFO:ece2cmor3.nemo2cmor:Creating time axes for table Omon from data in /net/bhw463/nobackup/users/reerink/cmip6-ec-earth-output/t143/001/t143_1m_19900101_19901231_opa_grid_V_3D.nc...
INFO:ece2cmor3.nemo2cmor:Creating depth axes for table Omon from data in /net/bhw463/nobackup/users/reerink/cmip6-ec-earth-output/t143/001/t143_1m_19900101_19901231_opa_grid_V_3D.nc ...
INFO:ece2cmor3.nemo2cmor:Creating extra axes for table Omon from data in /net/bhw463/nobackup/users/reerink/cmip6-ec-earth-output/t143/001/t143_1m_19900101_19901231_opa_grid_V_3D.nc ...

C Traceback:
! In function: cmor_axis
! called from: cmor_variable
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: Could not find all axes for this variable. 
! Check that all your axes name matches the ones found in 
! the table Omon. 
!
!
!!!!!!!!!!!!!!!!!!!!!!!!!


C Traceback:
! In function: cmor_variable
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: You are defining variable 'vo' (table Omon)  with 2 dimensions, when it should have 4
!
!!!!!!!!!!!!!!!!!!!!!!!!!

Traceback (most recent call last):
  File "/usr/people/reerink/anaconda2/envs/ece2cmor3/bin/ece2cmor", line 11, in <module>
    load_entry_point('ece2cmor3', 'console_scripts', 'ece2cmor')()
  File "/usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/ece2cmor.py", line 115, in main
    ece2cmorlib.perform_nemo_tasks(args.datadir, args.exp, startdate, length)
  File "/usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/ece2cmorlib.py", line 176, in perform_nemo_tasks
    nemo2cmor.execute(nemo_tasks)
  File "/usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/nemo2cmor.py", line 97, in execute
    execute_netcdf_task(dataset, task)
  File "/usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/nemo2cmor.py", line 136, in execute_netcdf_task
    varid = create_cmor_variable(task, dataset, axes)
  File "/usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/nemo2cmor.py", line 199, in create_cmor_variable
    original_name=str(srcvar))
  File "/usr/people/reerink/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/cmor/pywrapper.py", line 546, in variable
    missing_value, tolerance, positive, original_name, history, comment)
_cmor.CMORError: Problem with 'cmor.variable'. Please check the logfile (if defined).
`````

**Comment by aearamos** [comment]
This is the same issue as #284. I had errors with some other variables as well.

**Comment by goord** [comment]
Reverted previous fix, will look for another way to fix the msftyz cmorization

**Comment by treerink** [comment]
Ok revert fixed this.
Closing
