### ISSUE TITLE
Trouble with msftbarot with operation=instant: with time_instant  and time_instant_bounds

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#300]
When testing the cmorization of all CMIP6 NEMO output, we are now able to produce 285 variables (#281 is solved). However, the following stops the rest of the NEMO cmorization now:
`````
INFO:ece2cmor3.nemo2cmor:CMOR closed file ./cmor/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/piControl/r1i1p1f1/SImon/siforceintstry/gr/v20181102/siforceintstry_SImon_EC-Earth3_piControl_r1i1p1f1_gr_199001-199012.nc
Traceback (most recent call last):
  File "/usr/people/reerink/anaconda2/envs/ece2cmor3/bin/ece2cmor", line 11, in <module>
    load_entry_point('ece2cmor3', 'console_scripts', 'ece2cmor')()
  File "/usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/ece2cmor.py", line 112, in main
    ece2cmorlib.perform_nemo_tasks(args.datadir, args.exp, refdate)
  File "/usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/ece2cmorlib.py", line 177, in perform_nemo_tasks
    nemo2cmor.execute(nemo_tasks)
  File "/usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/nemo2cmor.py", line 96, in execute
    create_time_axes(dataset, task_list, table)
  File "/usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/nemo2cmor.py", line 259, in create_time_axes
    calendar=getattr(ds, "calendar", "gregorian"))
  File "cftime/_cftime.pyx", line 285, in cftime._cftime.num2date
OverflowError: Python int too large to convert to C long
`````

**Comment by goord** [comment]
Hi Thomas, we need to have a look at that file siforceintstry_SImon_EC-Earth3_piControl_r1i1p1f1_gr_199001-199012.nc to see why its time variable values are so large....

**Comment by treerink** [comment]
`````
ncdump  /net/bhw463/nobackup/users/reerink/cmip6-ec-earth-output/t151/001/t151_1m_19900101_19901231_opa_grid_U_2D.nc |grep time_instant
`````
gives:
`````
	double time_instant(time_counter) ;
		time_instant:standard_name = "time" ;
		time_instant:long_name = "Time axis" ;
		time_instant:calendar = "gregorian" ;
		time_instant:units = "seconds since 1800-01-01 00:00:00" ;
		time_instant:time_origin = "1800-01-01 00:00:00" ;
		time_instant:bounds = "time_instant_bounds" ;
	double time_instant_bounds(time_counter, axis_nbounds) ;
		msftbarot:coordinates = "time_instant nav_lat nav_lon" ;
 time_instant = _, _, _, _, _, _, _, _, _, _, _, _ ;
 time_instant_bounds =
`````
So the absence of the values of **time_instant** seems to be problematic.

**Comment by goord** [comment]
and what about those time bounds in that file? Do those have valid values?

**Comment by treerink** [comment]
In this file it is only the variable (cmor name:) **msftbarot** (on `grid_U_2D`) which uses the **time_instant** dimension axis. It refers to  **uoce_e3u_vsum_e2u_cumul** in the `field_def_nemo-opa.xml` file. Which includes the attribute settings: **operation="instant" freq_op="1mo"**.

As the **output_freq="1mo"** for  **msftbarot** there should be one time value per month (the last time step of the month), for this 1 year piece of the run that should be 12 numbers which agrees with the 12 empty "_" numbers in the **time_instant**.

The question remains why they have no value while the  **uoce_e3u_vsum_e2u_cumul** field definition sets the  **operation="instant"**?

The **time_instant_bounds** values are also empty when dumped with ncdump:
`````
ncdump -v  time_instant,time_instant_bounds  t166_1m_19900101_19901231_opa_grid_U_2D.nc
netcdf t166_1m_19900101_19901231_opa_grid_U_2D {
dimensions:
	axis_nbounds = 2 ;
	x = 362 ;
	y = 292 ;
	time_counter = UNLIMITED ; // (12 currently)
variables:
	float nav_lat(y, x) ;
		nav_lat:standard_name = "latitude" ;
		nav_lat:long_name = "Latitude" ;
		nav_lat:units = "degrees_north" ;
	float nav_lon(y, x) ;
		nav_lon:standard_name = "longitude" ;
		nav_lon:long_name = "Longitude" ;
		nav_lon:units = "degrees_east" ;
	double time_instant(time_counter) ;
		time_instant:standard_name = "time" ;
		time_instant:long_name = "Time axis" ;
		time_instant:calendar = "gregorian" ;
		time_instant:units = "seconds since 1800-01-01 00:00:00" ;
		time_instant:time_origin = "1800-01-01 00:00:00" ;
		time_instant:bounds = "time_instant_bounds" ;
	double time_instant_bounds(time_counter, axis_nbounds) ;
	double time_counter(time_counter) ;
		time_counter:axis = "T" ;
		time_counter:standard_name = "time" ;
		time_counter:long_name = "Time axis" ;
		time_counter:calendar = "gregorian" ;
		time_counter:units = "seconds since 1800-01-01 00:00:00" ;
		time_counter:time_origin = "1800-01-01 00:00:00" ;
		time_counter:bounds = "time_counter_bounds" ;
	double time_counter_bounds(time_counter, axis_nbounds) ;
	double time_centered(time_counter) ;
		time_centered:standard_name = "time" ;
		time_centered:long_name = "Time axis" ;
		time_centered:calendar = "gregorian" ;
		time_centered:units = "seconds since 1800-01-01 00:00:00" ;
		time_centered:time_origin = "1800-01-01 00:00:00" ;
		time_centered:bounds = "time_centered_bounds" ;
	double time_centered_bounds(time_counter, axis_nbounds) ;
	float msftbarot(time_counter, y, x) ;
		msftbarot:long_name = "ocean current along i-axis * e3u * e2u cumulated from southwest point" ;
		msftbarot:units = "kg s-1" ;
		msftbarot:online_operation = "instant" ;
		msftbarot:interval_operation = "1 month" ;
		msftbarot:interval_write = "1 month" ;
		msftbarot:cell_methods = "time: point" ;
		msftbarot:_FillValue = 1.e+20f ;
		msftbarot:missing_value = 1.e+20f ;
		msftbarot:coordinates = "time_instant nav_lat nav_lon" ;
	float tauuo(time_counter, y, x) ;
		tauuo:standard_name = "surface_downward_x_stress" ;
		tauuo:long_name = "Wind Stress along i-axis" ;
		tauuo:units = "N m-2" ;
		tauuo:online_operation = "average" ;
		tauuo:interval_operation = "2700 s" ;
		tauuo:interval_write = "1 month" ;
		tauuo:cell_methods = "time: mean (interval: 2700 s)" ;
		tauuo:_FillValue = 1.e+20f ;
		tauuo:missing_value = 1.e+20f ;
		tauuo:coordinates = "time_centered nav_lat nav_lon" ;

// global attributes:
		:name = "t166_1m_19900101_19901231_opa_grid_U_2D" ;
		:description = "Created by xios" ;
		:title = "Created by xios" ;
		:Conventions = "CF-1.6" ;
		:timeStamp = "2018-Nov-01 21:44:34 GMT" ;
		:uuid = "678aca4e-63bd-4898-babe-acca8790f4b2" ;
data:

 time_instant = _, _, _, _, _, _, _, _, _, _, _, _ ;

 time_instant_bounds =
  _, _,
  _, _,
  _, _,
  _, _,
  _, _,
  _, _,
  _, _,
  _, _,
  _, _,
  _, _,
  _, _,
  _, _ ;
}
`````
Though with ncview it looks like they are for each time step 0, 80896 ?

**Comment by goord** [comment]
Maybe something to report back to the shaconemo community?

**Comment by treerink** [comment]
It appears that with the output (in which all NEMO output is switched on) of an EC-Earth run that includes the XIOS-2.5 & Shaconemo updates and where the additional Poleward heat and salt transport & Atlantic/Pacific/Indian basins computation are switched on, the `time_instant` and `time_instant_bounds` have proper values. And with that the cmorization of the `Omon` variables `msftbarot`, `hfx`, `tauuo` runs without errors. However, with
`````
ece2cmor /net/bhw463/nobackup/users/reerink/cmip6-ec-earth-output/t011/001 --exp t011 --oce --conf ece2cmor3/resources/metadata-templates/cmip6-CMIP-piControl-metadata-template.json --vars ece2cmor3/resources/test-data-request/varlist-nemo-Omon-msftbarot.json
`````
we have the following warnings for instance for `msftbarot`:
`````
INFO:ece2cmor3.nemo2cmor:Executing 1 NEMO tasks...
INFO:ece2cmor3.nemo2cmor:Cmorizing NEMO tasks...
INFO:ece2cmor3.nemo2cmor:Creating time axes for table Omon from data in /net/bhw463/nobackup/users/reerink/cmip6-ec-earth-output/t011/001/t011_1m_19900101_19901231_opa_grid_U_2D.nc...
INFO:ece2cmor3.nemo2cmor:Creating time axis for table Omon using file /net/bhw463/nobackup/users/reerink/cmip6-ec-earth-output/t011/001/t011_1m_19900101_19901231_opa_grid_U_2D.nc...

C Traceback:
In function: cmor_check_monotonic
! called from: cmor_treat_axis_values
! called from: cmor_axis
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Warning: axis time (table: Omon) has bounds values that leave gaps
! (index 0): 51165.000000, 51165.000000, 51193.000000
!
!!!!!!!!!!!!!!!!!!!!!!!!!


C Traceback:
In function: cmor_check_monotonic
! called from: cmor_treat_axis_values
! called from: cmor_axis
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Warning: axis time (table: Omon) has bounds values that leave gaps
! (index 2): 51193.000000, 51193.000000, 51224.000000
!
!!!!!!!!!!!!!!!!!!!!!!!!!


C Traceback:
In function: cmor_check_monotonic
! called from: cmor_treat_axis_values
! called from: cmor_axis
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Warning: axis time (table: Omon) has bounds values that leave gaps
! (index 4): 51224.000000, 51224.000000, 51254.000000
!
!!!!!!!!!!!!!!!!!!!!!!!!!


C Traceback:
In function: cmor_check_monotonic
! called from: cmor_treat_axis_values
! called from: cmor_axis
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Warning: axis time (table: Omon) has bounds values that leave gaps
! (index 6): 51254.000000, 51254.000000, 51285.000000
!
!!!!!!!!!!!!!!!!!!!!!!!!!


C Traceback:
In function: cmor_check_monotonic
! called from: cmor_treat_axis_values
! called from: cmor_axis
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Warning: axis time (table: Omon) has bounds values that leave gaps
! (index 8): 51285.000000, 51285.000000, 51315.000000
!
!!!!!!!!!!!!!!!!!!!!!!!!!


C Traceback:
In function: cmor_check_monotonic
! called from: cmor_treat_axis_values
! called from: cmor_axis
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Warning: axis time (table: Omon) has bounds values that leave gaps
! (index 10): 51315.000000, 51315.000000, 51346.000000
!
!!!!!!!!!!!!!!!!!!!!!!!!!


C Traceback:
In function: cmor_check_monotonic
! called from: cmor_treat_axis_values
! called from: cmor_axis
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Warning: axis time (table: Omon) has bounds values that leave gaps
! (index 12): 51346.000000, 51346.000000, 51377.000000
!
!!!!!!!!!!!!!!!!!!!!!!!!!


C Traceback:
In function: cmor_check_monotonic
! called from: cmor_treat_axis_values
! called from: cmor_axis
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Warning: axis time (table: Omon) has bounds values that leave gaps
! (index 14): 51377.000000, 51377.000000, 51407.000000
!
!!!!!!!!!!!!!!!!!!!!!!!!!


C Traceback:
In function: cmor_check_monotonic
! called from: cmor_treat_axis_values
! called from: cmor_axis
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Warning: axis time (table: Omon) has bounds values that leave gaps
! (index 16): 51407.000000, 51407.000000, 51438.000000
!
!!!!!!!!!!!!!!!!!!!!!!!!!


C Traceback:
In function: cmor_check_monotonic
! called from: cmor_treat_axis_values
! called from: cmor_axis
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Warning: axis time (table: Omon) has bounds values that leave gaps
! (index 18): 51438.000000, 51438.000000, 51468.000000
!
!!!!!!!!!!!!!!!!!!!!!!!!!


C Traceback:
In function: cmor_check_monotonic
! called from: cmor_treat_axis_values
! called from: cmor_axis
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Warning: axis time (table: Omon) has bounds values that leave gaps
! (index 20): 51468.000000, 51468.000000, 51499.000000
!
!!!!!!!!!!!!!!!!!!!!!!!!!

INFO:ece2cmor3.nemo2cmor:Creating depth axes for table Omon from data in /net/bhw463/nobackup/users/reerink/cmip6-ec-earth-output/t011/001/t011_1m_19900101_19901231_opa_grid_U_2D.nc ...
INFO:ece2cmor3.nemo2cmor:Creating depth axes for table Omon using file /net/bhw463/nobackup/users/reerink/cmip6-ec-earth-output/t011/001/t011_1m_19900101_19901231_opa_grid_U_2D.nc...
INFO:ece2cmor3.nemo2cmor:Creating extra axes for table Omon from data in /net/bhw463/nobackup/users/reerink/cmip6-ec-earth-output/t011/001/t011_1m_19900101_19901231_opa_grid_U_2D.nc ...
INFO:ece2cmor3.nemo2cmor:Creating extra axes for table Omon using file /net/bhw463/nobackup/users/reerink/cmip6-ec-earth-output/t011/001/t011_1m_19900101_19901231_opa_grid_U_2D.nc...
INFO:ece2cmor3.nemo2cmor:cmorizing variable msftbarot in table Omon from msftbarot in file /net/bhw463/nobackup/users/reerink/cmip6-ec-earth-output/t011/001/t011_1m_19900101_19901231_opa_grid_U_2D.nc...
! ------
! CMOR is now closed.
! ------
! During execution we encountered:
!  11 Warning(s)
!   0 Error(s)
! ------
! Please review them.
! ------
! 
`````

**Comment by goord** [comment]
Hi @treerink I think the problem is here that ece2cmor3 doesn't pass instantaneous ocean variables correctly to cmor, let's have a look at this tomorrow.

**Comment by treerink** [comment]
The values of the time_instant and time_instant_bounds:
`````
ncdump -v  time_instant,time_instant_bounds cmip6-ec-earth-output/t011/001/t011_1m_19900101_19901231_opa_grid_U_2D.nc 
netcdf t011_1m_19900101_19901231_opa_grid_U_2D {
dimensions:
	axis_nbounds = 2 ;
	x = 362 ;
	y = 292 ;
	time_counter = UNLIMITED ; // (12 currently)
variables:
	float nav_lat(y, x) ;
		nav_lat:standard_name = "latitude" ;
		nav_lat:long_name = "Latitude" ;
		nav_lat:units = "degrees_north" ;
	float nav_lon(y, x) ;
		nav_lon:standard_name = "longitude" ;
		nav_lon:long_name = "Longitude" ;
		nav_lon:units = "degrees_east" ;
	double time_instant(time_counter) ;
		time_instant:standard_name = "time" ;
		time_instant:long_name = "Time axis" ;
		time_instant:calendar = "gregorian" ;
		time_instant:units = "seconds since 1800-01-01 00:00:00" ;
		time_instant:time_origin = "1800-01-01 00:00:00" ;
		time_instant:bounds = "time_instant_bounds" ;
	double time_instant_bounds(time_counter, axis_nbounds) ;
	double time_counter(time_counter) ;
		time_counter:axis = "T" ;
		time_counter:standard_name = "time" ;
		time_counter:long_name = "Time axis" ;
		time_counter:calendar = "gregorian" ;
		time_counter:units = "seconds since 1800-01-01 00:00:00" ;
		time_counter:time_origin = "1800-01-01 00:00:00" ;
		time_counter:bounds = "time_counter_bounds" ;
	double time_counter_bounds(time_counter, axis_nbounds) ;
	double time_centered(time_counter) ;
		time_centered:standard_name = "time" ;
		time_centered:long_name = "Time axis" ;
		time_centered:calendar = "gregorian" ;
		time_centered:units = "seconds since 1800-01-01 00:00:00" ;
		time_centered:time_origin = "1800-01-01 00:00:00" ;
		time_centered:bounds = "time_centered_bounds" ;
	double time_centered_bounds(time_counter, axis_nbounds) ;
	float msftbarot(time_counter, y, x) ;
		msftbarot:long_name = "ocean current along i-axis * e3u * e2u cumulated from southwest point" ;
		msftbarot:units = "kg s-1" ;
		msftbarot:online_operation = "instant" ;
		msftbarot:interval_operation = "1 month" ;
		msftbarot:interval_write = "1 month" ;
		msftbarot:cell_methods = "time: point" ;
		msftbarot:_FillValue = 1.e+20f ;
		msftbarot:missing_value = 1.e+20f ;
		msftbarot:coordinates = "time_instant nav_lat nav_lon" ;
	float hfx(time_counter, y, x) ;
		hfx:standard_name = "advectice_ocean_heat_x_transport" ;
		hfx:long_name = "ocean advective heat transport along i-axis" ;
		hfx:units = "W" ;
		hfx:online_operation = "average" ;
		hfx:interval_operation = "2700 s" ;
		hfx:interval_write = "1 month" ;
		hfx:cell_methods = "time: mean (interval: 2700 s)" ;
		hfx:_FillValue = 1.e+20f ;
		hfx:missing_value = 1.e+20f ;
		hfx:coordinates = "time_centered nav_lat nav_lon" ;
	float tauuo(time_counter, y, x) ;
		tauuo:standard_name = "surface_downward_x_stress" ;
		tauuo:long_name = "Wind Stress along i-axis" ;
		tauuo:units = "N m-2" ;
		tauuo:online_operation = "average" ;
		tauuo:interval_operation = "2700 s" ;
		tauuo:interval_write = "1 month" ;
		tauuo:cell_methods = "time: mean (interval: 2700 s)" ;
		tauuo:_FillValue = 1.e+20f ;
		tauuo:missing_value = 1.e+20f ;
		tauuo:coordinates = "time_centered nav_lat nav_lon" ;

// global attributes:
		:name = "t011_1m_19900101_19901231_opa_grid_U_2D" ;
		:description = "Created by xios" ;
		:title = "Created by xios" ;
		:Conventions = "CF-1.6" ;
		:timeStamp = "2018-Nov-12 23:46:19 GMT" ;
		:uuid = "18eb82b7-ca09-4135-b00f-fdb032560988" ;
data:

 time_instant = 5998492800, 6000912000, 6003590400, 6006182400, 6008860800, 
    6011452800, 6014131200, 6016809600, 6019401600, 6022080000, 6024672000, 
    6027350400 ;

 time_instant_bounds =
  5998492800, 5998492800,
  6000912000, 6000912000,
  6003590400, 6003590400,
  6006182400, 6006182400,
  6008860800, 6008860800,
  6011452800, 6011452800,
  6014131200, 6014131200,
  6016809600, 6016809600,
  6019401600, 6019401600,
  6022080000, 6022080000,
  6024672000, 6024672000,
  6027350400, 6027350400 ;
}
`````

**Comment by treerink** [comment]
From the `resources/cmip6-cmor-tables/Tables/CMIP6_Omon.json` it appears that `msftbarot` actually should be an **time averaged** variable, this in contrast to the definition of `uoce_e3u_vsum_e2u_cumul` in the `field_def_nemo-opa.xml` file to which `msftbarot` refers. So this is a wrong definition in this field_def file from CMIP6 perspective:
`````
        "msftbarot": {
            "frequency": "mon", 
            "modeling_realm": "ocean", 
            "standard_name": "ocean_barotropic_mass_streamfunction", 
            "units": "kg s-1", 
            "cell_methods": "area: mean where sea time: mean", 
            "cell_measures": "area: areacello", 
            "long_name": "Ocean Barotropic Mass Streamfunction", 
            "comment": "Streamfunction or its approximation for free surface models. See OMDP document for details.", 
            "dimensions": "longitude latitude time", 
            "out_name": "msftbarot", 
            "type": "real", 
            "positive": "", 
            "valid_min": "", 
            "valid_max": "", 
            "ok_min_mean_abs": "", 
            "ok_max_mean_abs": ""
        }, 
`````

**Comment by treerink** [comment]
After all updates this variable did not give any longer any  trouble during cmorization.

Concerning the correct operation: instant or average: this will pop-up in the check as proposed in #327.

So closing this issue.
