### ISSUE TITLE
Problem with newest cmor library: libhdf5.so.103: cannot open shared object file

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#316]
I am not able to update the `environment.yml` to:
`````
- cmor=2018.11.07.master.npy1.14=py27h9ac9557_0
- cdo=1.9.5=h249571a_5
`````
both complain about the `libhdf5.so.103`. Therefore in e2639fa9ae5fa80b8bc2d503d6d5fd4ddf3e5ffe cdo is updated to  cdo=1.9.4, and the cmor is still at the one but last version.

`````
ece2cmor -h
Traceback (most recent call last):
  File "/home/thomas/anaconda2/envs/ece2cmor3/bin/ece2cmor", line 11, in <module>
    load_entry_point('ece2cmor3==0.8.0', 'console_scripts', 'ece2cmor')()
  File "/home/thomas/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/thomas/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/home/thomas/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/home/thomas/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/thomas/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-0.8.0-py2.7.egg/ece2cmor3/ece2cmor.py", line 12, in <module>
    from ece2cmor3 import ece2cmorlib, taskloader, components, __version__
  File "/home/thomas/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-0.8.0-py2.7.egg/ece2cmor3/ece2cmorlib.py", line 3, in <module>
    import cmor
  File "/home/thomas/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/cmor/__init__.py", line 7, in <module>
    from cmor_const import *
  File "/home/thomas/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/cmor/cmor_const.py", line 1, in <module>
    import _cmor
ImportError: libhdf5.so.103: cannot open shared object file: No such file or directory
`````
And also, getting the same kind of error message, I was not able to update from cdo-1.9.4 to cdo-1.9.5
`````
cdo: error while loading shared libraries: libhdf5.so.103: cannot open shared object file: No such file or directory
`````

**Comment by treerink** [comment]
The problem seems to be part of the hdf5 1.10.1 / 1.10.2 dependency in the latest cmor library to which we try to update. Isuue posted at PCMDI: https://github.com/PCMDI/cmor/issues/416

**Comment by treerink** [comment]
See the progress of yesterday:
https://github.com/PCMDI/cmor/issues/416
So at:
https://anaconda.org/PCMDI/cmor/files
it seems there is now a new version available:
`````
linux:  cmor=3.3.3.2018.12.17.20.22.g309f4c6.npy1.14=py27ha5dfbcb_0    depending on:  cdms2, hdf5 >=1.10.3,<2.0a0, libgcc-ng >=7.3.0, libgfortran-ng >=7,<8.0a0, libnetcdf >=4.6.1,<5.0a0, numpy >=1.14.6,<2.0a0, ossuuid 1.6.2.*, python >=2.7,<2.8.0a0, udunits2

mac:    cmor=3.3.3.2018.12.17.12.25.g309f4c6.npy1.14=py27hd5f3a30_0    depending on:  cdms2, hdf5 >=1.10.3,<2.0a0, libgfortran >=3.0.1, libnetcdf >=4.6.1,<5.0a0, numpy >=1.14.6,<2.0a0, ossuuid 1.6.2.*, python >=2.7,<2.8.0a0, udunits2
`````
or:
`````
linux:  cmor=2018.12.17.master.npy1.14=py27h9ac9557_0    depending on: cdms2, hdf5 1.10.*, libgcc-ng >=7.3.0, libgfortran-ng >=7,<8.0a0, libnetcdf 4.6.*, numpy >=1.15.4,<2.0a0, ossuuid 1.6.2.*, python >=2.7,<2.8.0a0, udunits2

mac:    none
`````

**Comment by goord** [comment]
Hi Thomas, I tried this one but it is conflicting with the python-eccodes version...

**Comment by treerink** [comment]
Yes, I can confirm.

And the second one  `cmor=2018.12.17.master.npy1.14=py27h9ac9557_0` still gives the original error.

**Comment by goord** [comment]
Hi Thomas, I managed to get consistency with
```
- cmor=3.3.3.2018.12.17.20.22.g309f4c6.npy1.14=py27ha5dfbcb_0
- cdo=1.9.5
- python-eccodes=2.9.0
```
Tested this in clean environment, cdo is working properly and so is the cmor library

**Comment by treerink** [comment]
@tommibergman can you test the new environment for Mac OS?

For linux it is working now, so closing the issue.
