### ISSUE TITLE
Cmorization error with hfbasin: axis - table problem

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#321]
In trying to cmorize the full OPA-LIM output, after the successfull cmorization of 153 variables, I have an error here:
`````
INFO:ece2cmor3.nemo2cmor:cmorizing variable sltbasin in table EmonZ from sltbasin in file cmip6-ec-earth-output/t204/001/t204_1m_19900101_19901231_opa_grid_ptr_T_3basin_2D.nc...
INFO:ece2cmor3.nemo2cmor:Creating time axis for table Omon using file cmip6-ec-earth-output/t204/001/t204_1m_19900101_19901231_opa_grid_ptr_T_3basin_2D.nc...
INFO:ece2cmor3.nemo2cmor:Creating depth axes for table Omon using file cmip6-ec-earth-output/t204/001/t204_1m_19900101_19901231_opa_grid_ptr_T_3basin_2D.nc...
INFO:ece2cmor3.nemo2cmor:Creating extra axes for table Omon using file cmip6-ec-earth-output/t204/001/t204_1m_19900101_19901231_opa_grid_ptr_T_3basin_2D.nc...

C Traceback:
! In function: cmor_variable
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: While creating variable hfbasin, you are passing axis 43 (named lat) which has been defined using table 2 (EmonZ) but the current table is 1 (Omon) (and isgridaxis says: -1)
!
!!!!!!!!!!!!!!!!!!!!!!!!!

Traceback (most recent call last):
  File "/usr/people/reerink/anaconda2/envs/ece2cmor3/bin/ece2cmor", line 11, in <module>
    load_entry_point('ece2cmor3==0.8.0', 'console_scripts', 'ece2cmor')()
  File "/usr/people/reerink/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-0.8.0-py2.7.egg/ece2cmor3/ece2cmor.py", line 138, in main
    ece2cmorlib.perform_nemo_tasks(args.datadir, args.exp, refdate)
  File "/usr/people/reerink/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-0.8.0-py2.7.egg/ece2cmor3/ece2cmorlib.py", line 193, in perform_nemo_tasks
    nemo2cmor.execute(nemo_tasks)
  File "/usr/people/reerink/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-0.8.0-py2.7.egg/ece2cmor3/nemo2cmor.py", line 107, in execute
    execute_netcdf_task(dataset, task)
  File "/usr/people/reerink/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-0.8.0-py2.7.egg/ece2cmor3/nemo2cmor.py", line 146, in execute_netcdf_task
    varid = create_cmor_variable(task, dataset, axes)
  File "/usr/people/reerink/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-0.8.0-py2.7.egg/ece2cmor3/nemo2cmor.py", line 208, in create_cmor_variable
    original_name=str(srcvar))
  File "/usr/people/reerink/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/cmor/pywrapper.py", line 546, in variable
    missing_value, tolerance, positive, original_name, history, comment)
_cmor.CMORError: Problem with 'cmor.variable'. Please check the logfile (if defined).
`````

**Comment by treerink** [comment]
I have been running the following (so Gijs for you possible to run as well at KNMI out of the box):
`````
ece2cmor cmip6-ec-earth-output/t204/001/ --exp t204 --oce --conf ece2cmor3/resources/metadata-templates/cmip6-CMIP-piControl-metadata-template.json --vars ece2cmor3/resources/test-data-request/varlist-nemo-all.json --odir cmor-test-all
`````

**Comment by goord** [comment]
Hi @treerink can you try once more after commit a4ab36ad5b85cdbf8e846a25a8b6c1ceef607422?

**Comment by treerink** [comment]
Unfortunately it goes nearly immediately wrong now:
`````
INFO:ece2cmor3.nemo2cmor:Creating NEMO grids in CMOR...
ERROR:ece2cmor3.nemo2cmor:The grid opa_grid_1point consists of a single point which is not supported, dismissing variables masso in Omon,volo in Omon,zostoga in Omon,thetaoga in Omon,bigthetaoga in Omon,tosga in Omon,soga in Omon,sosga in Omon
Traceback (most recent call last):
  File "/usr/people/reerink/anaconda2/envs/ece2cmor3/bin/ece2cmor", line 11, in <module>
    load_entry_point('ece2cmor3==0.8.0', 'console_scripts', 'ece2cmor')()
  File "/usr/people/reerink/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-0.8.0-py2.7.egg/ece2cmor3/ece2cmor.py", line 138, in main
    ece2cmorlib.perform_nemo_tasks(args.datadir, args.exp, refdate)
  File "/usr/people/reerink/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-0.8.0-py2.7.egg/ece2cmor3/ece2cmorlib.py", line 193, in perform_nemo_tasks
    nemo2cmor.execute(nemo_tasks)
  File "/usr/people/reerink/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-0.8.0-py2.7.egg/ece2cmor3/nemo2cmor.py", line 82, in execute
    create_grids(tasks)
  File "/usr/people/reerink/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-0.8.0-py2.7.egg/ece2cmor3/nemo2cmor.py", line 384, in create_grids
    write_grid(grid, task_list)
  File "/usr/people/reerink/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-0.8.0-py2.7.egg/ece2cmor3/nemo2cmor.py", line 434, in write_grid
    key = (task.table, grid.name, latvars[0])
AttributeError: 'cmor_task' object has no attribute 'table'
`````

**Comment by treerink** [comment]
Goes better now ...
