### ISSUE TITLE
Difficulties with nosetests after full rebuilt of ece2cmor3 environment

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#352]
After reinstalling anaconda2-5.3.0 and re-configuring the conda 4.4 loading in bash:
`````
CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
If your shell is Bash or a Bourne variant, enable conda for the current user with

    $ echo ". /usr/people/reerink/anaconda2/etc/profile.d/conda.sh" >> ~/.bashrc

or, for all users, enable conda with

    $ sudo ln -s /usr/people/reerink/anaconda2/etc/profile.d/conda.sh /etc/profile.d/conda.sh

The options above will permanently enable the 'conda' command, but they do NOT
put conda's base (root) environment on PATH.  To do so, run

    $ conda activate

in your terminal, or to put the base environment on PATH permanently, run

    $ echo "conda activate" >> ~/.bashrc

Previous to conda 4.4, the recommended way to activate conda was to modify PATH in
your ~/.bashrc file.  You should manually remove the line that looks like

    export PATH="/usr/people/reerink/anaconda2/bin:$PATH"

^^^ The above line should NO LONGER be in your ~/.bashrc file! ^^^
`````
so using now once:
`````
echo ". /usr/people/reerink/anaconda2/etc/profile.d/conda.sh" >> ~/.bashrc
`````
and 
`````
conda activate
`````
instead of
`````
export PATH="${HOME}/anaconda2/bin:$PATH"
`````
im my aliases.

I get, while all other `ece2cmor` / `genecec` stuff seems to go fine, these errors for the `nosetests:`
`````
nosetests
.....................E.FF...............EEEEE.EEE....
C Traceback:
In function: cmor_outpath_exist
! called from: cmor_dataset_json
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Warning: You defined your output directory to be: '', but this
! directory does not exist. CMOR will create it!
!
!!!!!!!!!!!!!!!!!!!!!!!!!


C Traceback:
! In function: cmor_outpath_exist
! called from: cmor_dataset_json
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: CMOR was unable to create this directory 
! You do not have write permissions!
!
!!!!!!!!!!!!!!!!!!!!!!!!!

E
C Traceback:
In function: cmor_outpath_exist
! called from: cmor_dataset_json
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Warning: You defined your output directory to be: '', but this
! directory does not exist. CMOR will create it!
!
!!!!!!!!!!!!!!!!!!!!!!!!!


C Traceback:
! In function: cmor_outpath_exist
! called from: cmor_dataset_json
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: CMOR was unable to create this directory 
! You do not have write permissions!
!
!!!!!!!!!!!!!!!!!!!!!!!!!

E.
C Traceback:
In function: cmor_outpath_exist
! called from: cmor_dataset_json
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Warning: You defined your output directory to be: '', but this
! directory does not exist. CMOR will create it!
!
!!!!!!!!!!!!!!!!!!!!!!!!!


C Traceback:
! In function: cmor_outpath_exist
! called from: cmor_dataset_json
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: CMOR was unable to create this directory 
! You do not have write permissions!
!
!!!!!!!!!!!!!!!!!!!!!!!!!

EEEE.EEEEEEEEEE
======================================================================
ERROR: test_cell_measures (cmor_target_test.cmor_target_tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/people/reerink/cmorize/ece2cmor3/test/cmor_target_test.py", line 52, in test_cell_measures
    tasmin = [t for t in targets if t.table == "day" and t.variable == "tasmin"][0]
IndexError: list index out of range

======================================================================
ERROR: test_create_task (ece2cmor_test.ece2cmorlib_tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/people/reerink/cmorize/ece2cmor3/test/ece2cmor_test.py", line 28, in test_create_task
    ece2cmorlib_tests.init()
  File "/usr/people/reerink/cmorize/ece2cmor3/test/ece2cmor_test.py", line 15, in init
    ece2cmorlib.initialize()
  File "/usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/ece2cmorlib.py", line 64, in initialize
    validate_setup_settings()
  File "/usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/ece2cmorlib.py", line 95, in validate_setup_settings
    raise Exception("Cmorization table directory does not exist")
Exception: Cmorization table directory does not exist
-------------------- >> begin captured logging << --------------------
ece2cmor3.ece2cmorlib: ERROR: Cmorization table directory /usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/resources/tables does not exist
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_duplicate_task (ece2cmor_test.ece2cmorlib_tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/people/reerink/cmorize/ece2cmor3/test/ece2cmor_test.py", line 37, in test_duplicate_task
    ece2cmorlib_tests.init()
  File "/usr/people/reerink/cmorize/ece2cmor3/test/ece2cmor_test.py", line 15, in init
    ece2cmorlib.initialize()
  File "/usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/ece2cmorlib.py", line 64, in initialize
    validate_setup_settings()
  File "/usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/ece2cmorlib.py", line 95, in validate_setup_settings
    raise Exception("Cmorization table directory does not exist")
Exception: Cmorization table directory does not exist
-------------------- >> begin captured logging << --------------------
ece2cmor3.ece2cmorlib: ERROR: Cmorization table directory /usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/resources/tables does not exist
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_initialize (ece2cmor_test.ece2cmorlib_tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/people/reerink/cmorize/ece2cmor3/test/ece2cmor_test.py", line 18, in test_initialize
    ece2cmorlib_tests.init()
  File "/usr/people/reerink/cmorize/ece2cmor3/test/ece2cmor_test.py", line 15, in init
    ece2cmorlib.initialize()
  File "/usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/ece2cmorlib.py", line 64, in initialize
    validate_setup_settings()
  File "/usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/ece2cmorlib.py", line 95, in validate_setup_settings
    raise Exception("Cmorization table directory does not exist")
Exception: Cmorization table directory does not exist
-------------------- >> begin captured logging << --------------------
ece2cmor3.ece2cmorlib: ERROR: Cmorization table directory /usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/resources/tables does not exist
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_lookup_target (ece2cmor_test.ece2cmorlib_tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/people/reerink/cmorize/ece2cmor3/test/ece2cmor_test.py", line 22, in test_lookup_target
    ece2cmorlib_tests.init()
  File "/usr/people/reerink/cmorize/ece2cmor3/test/ece2cmor_test.py", line 15, in init
    ece2cmorlib.initialize()
  File "/usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/ece2cmorlib.py", line 64, in initialize
    validate_setup_settings()
  File "/usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/ece2cmorlib.py", line 95, in validate_setup_settings
    raise Exception("Cmorization table directory does not exist")
Exception: Cmorization table directory does not exist
-------------------- >> begin captured logging << --------------------
ece2cmor3.ece2cmorlib: ERROR: Cmorization table directory /usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/resources/tables does not exist
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_expr_var (grib_filter_test.grib_filter_test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/people/reerink/cmorize/ece2cmor3/test/grib_filter_test.py", line 92, in test_expr_var
    ece2cmorlib.initialize()
  File "/usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/ece2cmorlib.py", line 64, in initialize
    validate_setup_settings()
  File "/usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/ece2cmorlib.py", line 95, in validate_setup_settings
    raise Exception("Cmorization table directory does not exist")
Exception: Cmorization table directory does not exist
-------------------- >> begin captured logging << --------------------
ece2cmor3.grib_filter: INFO: Searching for previous month file of /usr/people/reerink/cmorize/ece2cmor3/test/test_data/ifs/001/ICMGGECE3+199001.csv
ece2cmor3.grib_filter: INFO: Searching for previous month file of /usr/people/reerink/cmorize/ece2cmor3/test/test_data/ifs/001/ICMSHECE3+199001.csv
ece2cmor3.ece2cmorlib: ERROR: Cmorization table directory /usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/resources/tables does not exist
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_pressure_var (grib_filter_test.grib_filter_test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/people/reerink/cmorize/ece2cmor3/test/grib_filter_test.py", line 120, in test_pressure_var
    ece2cmorlib.initialize()
  File "/usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/ece2cmorlib.py", line 64, in initialize
    validate_setup_settings()
  File "/usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/ece2cmorlib.py", line 95, in validate_setup_settings
    raise Exception("Cmorization table directory does not exist")
Exception: Cmorization table directory does not exist
-------------------- >> begin captured logging << --------------------
ece2cmor3.grib_filter: INFO: Searching for previous month file of /usr/people/reerink/cmorize/ece2cmor3/test/test_data/ifs/001/ICMGGECE3+199001.csv
ece2cmor3.grib_filter: INFO: Searching for previous month file of /usr/people/reerink/cmorize/ece2cmor3/test/test_data/ifs/001/ICMSHECE3+199001.csv
ece2cmor3.ece2cmorlib: ERROR: Cmorization table directory /usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/resources/tables does not exist
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_surf_var (grib_filter_test.grib_filter_test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/people/reerink/cmorize/ece2cmor3/test/grib_filter_test.py", line 65, in test_surf_var
    ece2cmorlib.initialize()
  File "/usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/ece2cmorlib.py", line 64, in initialize
    validate_setup_settings()
  File "/usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/ece2cmorlib.py", line 95, in validate_setup_settings
    raise Exception("Cmorization table directory does not exist")
Exception: Cmorization table directory does not exist
-------------------- >> begin captured logging << --------------------
ece2cmor3.grib_filter: INFO: Searching for previous month file of /usr/people/reerink/cmorize/ece2cmor3/test/test_data/ifs/001/ICMGGECE3+199001.csv
ece2cmor3.grib_filter: INFO: Searching for previous month file of /usr/people/reerink/cmorize/ece2cmor3/test/test_data/ifs/001/ICMSHECE3+199001.csv
ece2cmor3.ece2cmorlib: ERROR: Cmorization table directory /usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/resources/tables does not exist
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_validate_tasks (grib_filter_test.grib_filter_test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/people/reerink/cmorize/ece2cmor3/test/grib_filter_test.py", line 43, in test_validate_tasks
    ece2cmorlib.initialize()
  File "/usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/ece2cmorlib.py", line 64, in initialize
    validate_setup_settings()
  File "/usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/ece2cmorlib.py", line 95, in validate_setup_settings
    raise Exception("Cmorization table directory does not exist")
Exception: Cmorization table directory does not exist
-------------------- >> begin captured logging << --------------------
ece2cmor3.grib_filter: INFO: Searching for previous month file of /usr/people/reerink/cmorize/ece2cmor3/test/test_data/ifs/001/ICMGGECE3+199001.csv
ece2cmor3.grib_filter: INFO: Searching for previous month file of /usr/people/reerink/cmorize/ece2cmor3/test/test_data/ifs/001/ICMSHECE3+199001.csv
ece2cmor3.ece2cmorlib: ERROR: Cmorization table directory /usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/resources/tables does not exist
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_cmor_single_task (nemo2cmor_test.nemo2cmor_tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/people/reerink/cmorize/ece2cmor3/test/nemo2cmor_test.py", line 122, in test_cmor_single_task
    cmor.dataset_json(conf_path)
  File "/usr/people/reerink/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/cmor/pywrapper.py", line 909, in dataset_json
    return _cmor.dataset_json(rcfile)
CMORError: Problem with 'cmor.dataset_json'. Please check the logfile (if defined).

======================================================================
ERROR: test_cmor_single_task3d (nemo2cmor_test.nemo2cmor_tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/people/reerink/cmorize/ece2cmor3/test/nemo2cmor_test.py", line 166, in test_cmor_single_task3d
    cmor.dataset_json(conf_path)
  File "/usr/people/reerink/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/cmor/pywrapper.py", line 909, in dataset_json
    return _cmor.dataset_json(rcfile)
CMORError: Problem with 'cmor.dataset_json'. Please check the logfile (if defined).

======================================================================
ERROR: test_init_nemo2cmor (nemo2cmor_test.nemo2cmor_tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/people/reerink/cmorize/ece2cmor3/test/nemo2cmor_test.py", line 157, in test_init_nemo2cmor
    cmor.dataset_json(conf_path)
  File "/usr/people/reerink/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/cmor/pywrapper.py", line 909, in dataset_json
    return _cmor.dataset_json(rcfile)
CMORError: Problem with 'cmor.dataset_json'. Please check the logfile (if defined).

======================================================================
ERROR: test_postproc_daymax (postproc_test.ifs2cmor_tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/people/reerink/cmorize/ece2cmor3/test/postproc_test.py", line 44, in test_postproc_daymax
    target = [t for t in targets if t.variable == "sfcWindmax" and t.table == "day"][0]
IndexError: list index out of range

======================================================================
ERROR: test_postproc_gridmean (postproc_test.ifs2cmor_tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/people/reerink/cmorize/ece2cmor3/test/postproc_test.py", line 19, in test_postproc_gridmean
    target = [t for t in targets if t.variable == "clwvi" and t.table == "CFday"][0]
IndexError: list index out of range

======================================================================
ERROR: test_postproc_maxwindspeed (postproc_test.ifs2cmor_tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/people/reerink/cmorize/ece2cmor3/test/postproc_test.py", line 76, in test_postproc_maxwindspeed
    target = [t for t in targets if t.variable == "sfcWindmax" and t.table == "day"][0]
IndexError: list index out of range

======================================================================
ERROR: test_postproc_tasmax (postproc_test.ifs2cmor_tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/people/reerink/cmorize/ece2cmor3/test/postproc_test.py", line 54, in test_postproc_tasmax
    target = [t for t in targets if t.variable == "tasmax" and t.table == "Amon"][0]
IndexError: list index out of range

======================================================================
ERROR: test_postproc_wap500 (postproc_test.ifs2cmor_tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/people/reerink/cmorize/ece2cmor3/test/postproc_test.py", line 87, in test_postproc_wap500
    target = [t for t in targets if t.variable == "wap500" and t.table == "CFday"][0]
IndexError: list index out of range

======================================================================
ERROR: test_postproc_windspeed (postproc_test.ifs2cmor_tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/people/reerink/cmorize/ece2cmor3/test/postproc_test.py", line 64, in test_postproc_windspeed
    target = [t for t in targets if t.variable == "sfcWind" and t.table == "6hrPlevPt"][0]
IndexError: list index out of range

======================================================================
ERROR: test_load_avars (taskloader_test.taskloader_test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/people/reerink/cmorize/ece2cmor3/test/taskloader_test.py", line 25, in test_load_avars
    ece2cmorlib.initialize()
  File "/usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/ece2cmorlib.py", line 64, in initialize
    validate_setup_settings()
  File "/usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/ece2cmorlib.py", line 95, in validate_setup_settings
    raise Exception("Cmorization table directory does not exist")
Exception: Cmorization table directory does not exist
-------------------- >> begin captured logging << --------------------
ece2cmor3.ece2cmorlib: ERROR: Cmorization table directory /usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/resources/tables does not exist
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_load_clt (taskloader_test.taskloader_test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/people/reerink/cmorize/ece2cmor3/test/taskloader_test.py", line 14, in test_load_clt
    ece2cmorlib.initialize()
  File "/usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/ece2cmorlib.py", line 64, in initialize
    validate_setup_settings()
  File "/usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/ece2cmorlib.py", line 95, in validate_setup_settings
    raise Exception("Cmorization table directory does not exist")
Exception: Cmorization table directory does not exist
-------------------- >> begin captured logging << --------------------
ece2cmor3.ece2cmorlib: ERROR: Cmorization table directory /usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/resources/tables does not exist
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_load_expressions (taskloader_test.taskloader_test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/people/reerink/cmorize/ece2cmor3/test/taskloader_test.py", line 70, in test_load_expressions
    ece2cmorlib.initialize()
  File "/usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/ece2cmorlib.py", line 64, in initialize
    validate_setup_settings()
  File "/usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/ece2cmorlib.py", line 95, in validate_setup_settings
    raise Exception("Cmorization table directory does not exist")
Exception: Cmorization table directory does not exist
-------------------- >> begin captured logging << --------------------
ece2cmor3.ece2cmorlib: ERROR: Cmorization table directory /usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/resources/tables does not exist
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_load_oavars (taskloader_test.taskloader_test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/people/reerink/cmorize/ece2cmor3/test/taskloader_test.py", line 44, in test_load_oavars
    ece2cmorlib.initialize()
  File "/usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/ece2cmorlib.py", line 64, in initialize
    validate_setup_settings()
  File "/usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/ece2cmorlib.py", line 95, in validate_setup_settings
    raise Exception("Cmorization table directory does not exist")
Exception: Cmorization table directory does not exist
-------------------- >> begin captured logging << --------------------
ece2cmor3.ece2cmorlib: ERROR: Cmorization table directory /usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/resources/tables does not exist
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_load_ovars (taskloader_test.taskloader_test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/people/reerink/cmorize/ece2cmor3/test/taskloader_test.py", line 35, in test_load_ovars
    ece2cmorlib.initialize()
  File "/usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/ece2cmorlib.py", line 64, in initialize
    validate_setup_settings()
  File "/usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/ece2cmorlib.py", line 95, in validate_setup_settings
    raise Exception("Cmorization table directory does not exist")
Exception: Cmorization table directory does not exist
-------------------- >> begin captured logging << --------------------
ece2cmor3.ece2cmorlib: ERROR: Cmorization table directory /usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/resources/tables does not exist
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_load_tos (taskloader_test.taskloader_test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/people/reerink/cmorize/ece2cmor3/test/taskloader_test.py", line 79, in test_load_tos
    ece2cmorlib.initialize()
  File "/usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/ece2cmorlib.py", line 64, in initialize
    validate_setup_settings()
  File "/usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/ece2cmorlib.py", line 95, in validate_setup_settings
    raise Exception("Cmorization table directory does not exist")
Exception: Cmorization table directory does not exist
-------------------- >> begin captured logging << --------------------
ece2cmor3.ece2cmorlib: ERROR: Cmorization table directory /usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/resources/tables does not exist
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_load_unit_conv (taskloader_test.taskloader_test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/people/reerink/cmorize/ece2cmor3/test/taskloader_test.py", line 55, in test_load_unit_conv
    ece2cmorlib.initialize()
  File "/usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/ece2cmorlib.py", line 64, in initialize
    validate_setup_settings()
  File "/usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/ece2cmorlib.py", line 95, in validate_setup_settings
    raise Exception("Cmorization table directory does not exist")
Exception: Cmorization table directory does not exist
-------------------- >> begin captured logging << --------------------
ece2cmor3.ece2cmorlib: ERROR: Cmorization table directory /usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/resources/tables does not exist
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: test_make_CMIP6_vars (cmor_target_test.cmor_target_tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/people/reerink/cmorize/ece2cmor3/test/cmor_target_test.py", line 41, in test_make_CMIP6_vars
    ok_(len(targets) > 0)
AssertionError: None

======================================================================
FAIL: test_make_Omon_vars (cmor_target_test.cmor_target_tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/people/reerink/cmorize/ece2cmor3/test/cmor_target_test.py", line 29, in test_make_Omon_vars
    ok_(len(targets) > 0)
AssertionError: None

----------------------------------------------------------------------
Ran 71 tests in 34.005s

FAILED (errors=25, failures=2)
`````

**Comment by goord** [comment]
have you run
```
git submodule update --init
```
?

**Comment by treerink** [comment]
Ok after:
`````
git submodule update --init --recursive
`````
it works again. However, remarkable because in principle the tables were already update, only anaconda was reinstalled and the environment rebuilt. Anyway obviously this was now needed (but usually with only a rebuilt of the environment it is not (if the cmor tables are already update).
