### ISSUE TITLE
Masscello cmorization fails with Elpin

### ISSUE THREAD

**Issue by aearamos** [EC-Earth/ece2cmor3#355]
Hi Gijs,

On Monday I started running the cmorisation with Elpin to mask the land and got some errors when trying to cmorise masscello, probably because of the masking. Here is the error:

INFO:ece2cmor3.nemo2cmor:cmorizing variable masscello in table Ofx from masscello in file /gpfs/scratch/pr1eel00/pr1eel17/a1mz/18500101/fc0/runtime/output/nemo/001/a1mz_1y_18500101_18500131_opa_grid_T_3D.nc...
Traceback (most recent call last):
  File "./ece2cmor.py", line 151, in <module>
    main()
  File "./ece2cmor.py", line 136, in main
    ece2cmorlib.perform_nemo_tasks(args.datadir, args.exp, refdate)
  File "/gpfs/scratch/pr1eel00/pr1eel17/a1mz/auto-ecearth3/ece2cmor/ece2cmor3/ece2cmorlib.py", line 190, in perform_nemo_tasks
    nemo2cmor.execute(nemo_tasks)
  File "/gpfs/scratch/pr1eel00/pr1eel17/a1mz/auto-ecearth3/ece2cmor/ece2cmor3/nemo2cmor.py", line 108, in execute
    execute_netcdf_task(dataset, task)
  File "/gpfs/scratch/pr1eel00/pr1eel17/a1mz/auto-ecearth3/ece2cmor/ece2cmor3/nemo2cmor.py", line 171, in execute_netcdf_task
    time_selection=time_sel)
  File "/gpfs/scratch/pr1eel00/pr1eel17/a1mz/auto-ecearth3/ece2cmor/ece2cmor3/cmor_utils.py", line 256, in netcdf2cmor
    chunk = int(math.floor(4.0E+9 / (8 * size)))  # Use max 4 GB of memory
ZeroDivisionError: float division by zero

It makes sense to me that we get an error when the mask is zero but is there a way to still compute msscello? Thanks!

**Comment by goord** [comment]
Hi Arthur, it appears that netcdf says that your masscello variable has size 0, which is a bit strange. You can visualize the variable with ncview right?  Perhaps you can send me the file over mail?

**Comment by aearamos** [comment]
Hi Gijs, I had a problem with my xml file, thus the issue. I managed to find the error and fixed it, so closing the issue.
