### ISSUE TITLE
Cmorization error for Omon hfibthermds

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#387]
Trouble with the by #381 new added variable `hfibthermds` from the `Omon` table:

`````
C Traceback:
! In function: cmor_axis
! called from: cmor_variable
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: Could not find all axes for this variable. 
! Check that all your axes name matches the ones found in 
! the table Omon. 
!
!
!!!!!!!!!!!!!!!!!!!!!!!!!

Traceback (most recent call last):
  File "/usr/people/reerink/anaconda2/envs/ece2cmor3/bin/ece2cmor", line 11, in <module>
    load_entry_point('ece2cmor3==0.8.0', 'console_scripts', 'ece2cmor')()
  File "/usr/people/reerink/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-0.8.0-py2.7.egg/ece2cmor3/ece2cmor.py", line 147, in main
    ece2cmorlib.perform_nemo_tasks(args.datadir, args.exp, refdate)
  File "/usr/people/reerink/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-0.8.0-py2.7.egg/ece2cmor3/ece2cmorlib.py", line 193, in perform_nemo_tasks
    nemo2cmor.execute(nemo_tasks)
  File "/usr/people/reerink/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-0.8.0-py2.7.egg/ece2cmor3/nemo2cmor.py", line 108, in execute
    execute_netcdf_task(dataset, task)
  File "/usr/people/reerink/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-0.8.0-py2.7.egg/ece2cmor3/nemo2cmor.py", line 147, in execute_netcdf_task
    varid = create_cmor_variable(task, dataset, axes)
  File "/usr/people/reerink/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-0.8.0-py2.7.egg/ece2cmor3/nemo2cmor.py", line 209, in create_cmor_variable
    original_name=str(srcvar))
  File "/usr/people/reerink/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/cmor/pywrapper.py", line 546, in variable
    missing_value, tolerance, positive, original_name, history, comment)
_cmor.CMORError: Problem with 'cmor.variable'. Please check the logfile (if defined).
`````

**Comment by treerink** [comment]
This 3D `hfibthermds`variable in the data request  is identified with the 2D NEMO code `hflx_cal_cea` variable, but it seems a misidentification. The 2D variant is already identified by Shaconemo and present. The field_def shows that the NEMO code variable `hflx_cal_cea` is indeed a 2D variable, while the data request asks for a 3D `hfibthermds`variable.

So this variable has to be set to dummy again in the ping file.

**Comment by treerink** [comment]
The `hfibthermds` variable is set back to dummy status in th eping file, and all followup steps have been repeated to clean for this misidentification.
