### ISSUE TITLE
Cmorization error with zhalfo for table Omon: depth_coord axis not known

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#388]
Trouble with the by #381 new added variable `zhalfo` from the `Omon` table:
`````
C Traceback:
! In function: cmor_variable
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: You defined variable 'zhalfo' (table Omon) with axis id 'depth_coord' which is not part of this variable according to your table, it says: ( time olevhalf latitude longitude )
!
!!!!!!!!!!!!!!!!!!!!!!!!!

Traceback (most recent call last):
  File "/usr/people/reerink/anaconda2/envs/ece2cmor3/bin/ece2cmor", line 11, in <module>
    load_entry_point('ece2cmor3==0.8.0', 'console_scripts', 'ece2cmor')()
  File "/usr/people/reerink/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-0.8.0-py2.7.egg/ece2cmor3/ece2cmor.py", line 147, in main
    ece2cmorlib.perform_nemo_tasks(args.datadir, args.exp, refdate)
  File "/usr/people/reerink/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-0.8.0-py2.7.egg/ece2cmor3/ece2cmorlib.py", line 193, in perform_nemo_tasks
    nemo2cmor.execute(nemo_tasks)
  File "/usr/people/reerink/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-0.8.0-py2.7.egg/ece2cmor3/nemo2cmor.py", line 108, in execute
    execute_netcdf_task(dataset, task)
  File "/usr/people/reerink/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-0.8.0-py2.7.egg/ece2cmor3/nemo2cmor.py", line 147, in execute_netcdf_task
    varid = create_cmor_variable(task, dataset, axes)
  File "/usr/people/reerink/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-0.8.0-py2.7.egg/ece2cmor3/nemo2cmor.py", line 209, in create_cmor_variable
    original_name=str(srcvar))
  File "/usr/people/reerink/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/cmor/pywrapper.py", line 546, in variable
    missing_value, tolerance, positive, original_name, history, comment)
_cmor.CMORError: Problem with 'cmor.variable'. Please check the logfile (if defined).
`````

**Comment by treerink** [comment]
This variable can be found in the file *_1m_*_opa_grid_T_3D.nc file.

The `olevhalf` dimension is not yet implemented in ece2cmor3, see: grid_shape="longitude latitude olevhalf time"

**Comment by goord** [comment]
Hi @treerink can you try again with the olevhalf-fix branch?

**Comment by treerink** [comment]
@goord 

I tested it with the following:
`````
ece2cmor cmip6-ec-earth-output/t306/001/ --exp t306 --nemo --conf ece2cmor3/resources/metadata-templates/cmip6-CMIP-piControl-metadata-template.json --vars ece2cmor3/resources/test-data-request/varlist-nemo-zhalfo.json --odir cmor-test-zhalfo-306 >& log-cmip6-cmorizing-nemo-test-zhalfo-t306 &
`````

But get an error still:
`````
2019-03-05 12:06:30 INFO:ece2cmor3.taskloader: Found 2 cmor target variables in input variable list.
2019-03-05 12:06:30 INFO:ece2cmor3.taskloader: Created 2 ece2cmor tasks from input variable list.
2019-03-05 12:06:30 INFO:ece2cmor3.ece2cmorlib: Selected 2 NEMO tasks from 2 input tasks
2019-03-05 12:06:30 INFO:ece2cmor3.nemo2cmor: Looking up variables in files...
2019-03-05 12:06:30 ERROR:ece2cmor3.nemo2cmor: Variable zhalfo needed for zhalfo in table Oclim was not found in NEMO output files... skipping task
2019-03-05 12:06:30 INFO:ece2cmor3.nemo2cmor: Creating NEMO grids in CMOR...
2019-03-05 12:06:31 INFO:ece2cmor3.nemo2cmor: Executing 1 NEMO tasks...
2019-03-05 12:06:31 INFO:ece2cmor3.nemo2cmor: Cmorizing NEMO tasks...
2019-03-05 12:06:31 INFO:ece2cmor3.nemo2cmor: Start cmorization of zhalfo in table Omon
2019-03-05 12:06:31 INFO:ece2cmor3.nemo2cmor: Creating time axes for table Omon from data in cmip6-ec-earth-output/t306/001/t306_1m_19900101_19901231_opa_grid_T_3D.nc...
2019-03-05 12:06:31 INFO:ece2cmor3.nemo2cmor: Creating time axis for table Omon using file cmip6-ec-earth-output/t306/001/t306_1m_19900101_19901231_opa_grid_T_3D.nc...
2019-03-05 12:06:31 INFO:ece2cmor3.nemo2cmor: Creating depth axes for table Omon from data in cmip6-ec-earth-output/t306/001/t306_1m_19900101_19901231_opa_grid_T_3D.nc ...
2019-03-05 12:06:31 INFO:ece2cmor3.nemo2cmor: Creating depth axes for table Omon using file cmip6-ec-earth-output/t306/001/t306_1m_19900101_19901231_opa_grid_T_3D.nc...
2019-03-05 12:06:31 INFO:ece2cmor3.nemo2cmor: Creating extra axes for table Omon from data in cmip6-ec-earth-output/t306/001/t306_1m_19900101_19901231_opa_grid_T_3D.nc ...
2019-03-05 12:06:31 INFO:ece2cmor3.nemo2cmor: Creating extra axes for table Omon using file cmip6-ec-earth-output/t306/001/t306_1m_19900101_19901231_opa_grid_T_3D.nc...

C Traceback:)
! In function: cmor_variable
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: You defined variable 'zhalfo' (table Omon) with axis id 'depth_coord' which is not part of this variable according to your table, it says: ( time olevhalf latitude longitude )
!
!!!!!!!!!!!!!!!!!!!!!!!!!

Traceback (most recent call last):
  File "/usr/people/reerink/anaconda2/envs/ece2cmor3/bin/ece2cmor", line 11, in <module>
    load_entry_point('ece2cmor3==0.9.0', 'console_scripts', 'ece2cmor')()
  File "/usr/people/reerink/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-0.9.0-py2.7.egg/ece2cmor3/ece2cmor.py", line 152, in main
    ece2cmorlib.perform_nemo_tasks(args.datadir, args.exp, refdate)
  File "/usr/people/reerink/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-0.9.0-py2.7.egg/ece2cmor3/ece2cmorlib.py", line 193, in perform_nemo_tasks
    nemo2cmor.execute(nemo_tasks)
  File "/usr/people/reerink/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-0.9.0-py2.7.egg/ece2cmor3/nemo2cmor.py", line 108, in execute
    execute_netcdf_task(dataset, task)
  File "/usr/people/reerink/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-0.9.0-py2.7.egg/ece2cmor3/nemo2cmor.py", line 147, in execute_netcdf_task
    varid = create_cmor_variable(task, dataset, axes)
  File "/usr/people/reerink/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-0.9.0-py2.7.egg/ece2cmor3/nemo2cmor.py", line 209, in create_cmor_variable
    original_name=str(srcvar))
  File "/usr/people/reerink/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/cmor/pywrapper.py", line 546, in variable
    missing_value, tolerance, positive, original_name, history, comment)
_cmor.CMORError: Problem with 'cmor.variable'. Please check the logfile (if defined).
`````

**Comment by treerink** [comment]
After the change in b9c5d112f8cc4e792f1881522b81676323145b47 in the `olevhalf-fix` branch, we now have the error:
`````
2019-03-06 10:48:23 INFO:ece2cmor3.taskloader: Found 2 cmor target variables in input variable list.
2019-03-06 10:48:23 INFO:ece2cmor3.taskloader: Created 2 ece2cmor tasks from input variable list.
2019-03-06 10:48:23 INFO:ece2cmor3.ece2cmorlib: Selected 2 NEMO tasks from 2 input tasks
2019-03-06 10:48:23 INFO:ece2cmor3.nemo2cmor: Looking up variables in files...
2019-03-06 10:48:23 ERROR:ece2cmor3.nemo2cmor: Variable zhalfo needed for zhalfo in table Oclim was not found in NEMO output files... skipping task
2019-03-06 10:48:23 INFO:ece2cmor3.nemo2cmor: Creating NEMO grids in CMOR...
2019-03-06 10:48:24 INFO:ece2cmor3.nemo2cmor: Executing 1 NEMO tasks...
2019-03-06 10:48:24 INFO:ece2cmor3.nemo2cmor: Cmorizing NEMO tasks...
2019-03-06 10:48:24 INFO:ece2cmor3.nemo2cmor: Start cmorization of zhalfo in table Omon
2019-03-06 10:48:24 INFO:ece2cmor3.nemo2cmor: Creating time axes for table Omon from data in cmip6-ec-earth-output/t306/001/t306_1m_19900101_19901231_opa_grid_T_3D.nc...
2019-03-06 10:48:24 INFO:ece2cmor3.nemo2cmor: Creating time axis for table Omon using file cmip6-ec-earth-output/t306/001/t306_1m_19900101_19901231_opa_grid_T_3D.nc...
2019-03-06 10:48:24 INFO:ece2cmor3.nemo2cmor: Creating depth axes for table Omon from data in cmip6-ec-earth-output/t306/001/t306_1m_19900101_19901231_opa_grid_T_3D.nc ...
2019-03-06 10:48:24 INFO:ece2cmor3.nemo2cmor: Creating depth axes for table Omon using file cmip6-ec-earth-output/t306/001/t306_1m_19900101_19901231_opa_grid_T_3D.nc...

C Traceback:)
! In function: cmor_treat_axis_values
! called from: cmor_axis
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: axis 4 (olevhalf, table: Omon): cmor and user units are
! incompatible:  and m
!
!!!!!!!!!!!!!!!!!!!!!!!!!


C Traceback:)
! In function: cmor_treat_axis_values
! called from: cmor_axis
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: axis 4 (olevhalf, table: Omon): cmor and user units are
! incompatible:  and m
!
!!!!!!!!!!!!!!!!!!!!!!!!!

Traceback (most recent call last):
  File "/usr/people/reerink/anaconda2/envs/ece2cmor3/bin/ece2cmor", line 11, in <module>
    load_entry_point('ece2cmor3==0.9.0', 'console_scripts', 'ece2cmor')()
  File "/usr/people/reerink/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-0.9.0-py2.7.egg/ece2cmor3/ece2cmor.py", line 152, in main
    ece2cmorlib.perform_nemo_tasks(args.datadir, args.exp, refdate)
  File "/usr/people/reerink/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-0.9.0-py2.7.egg/ece2cmor3/ece2cmorlib.py", line 193, in perform_nemo_tasks
    nemo2cmor.execute(nemo_tasks)
  File "/usr/people/reerink/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-0.9.0-py2.7.egg/ece2cmor3/nemo2cmor.py", line 103, in execute
    create_depth_axes(dataset, task_list, table)
  File "/usr/people/reerink/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-0.9.0-py2.7.egg/ece2cmor3/nemo2cmor.py", line 244, in create_depth_axes
    z_axis_id = cmor.axis(table_entry=entry, units=units, coord_vals=zvar[:], cell_bounds=b)
  File "/usr/people/reerink/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/cmor/pywrapper.py", line 454, in axis
    type, cell_bounds, cbnds, interval)
_cmor.CMORError: Problem with 'cmor.axis'. Please check the logfile (if defined).
`````

**Comment by treerink** [comment]
When changing the unit of `olevhalf` in "`m`" in `CMIP6_coordinate.json` (which is currently empty, see line 1032 in the current version in: `https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_coordinate.json`), the problem seems solved. Therefore going to post an issue at the Github of the cmor tables.

**Comment by treerink** [comment]
See https://github.com/PCMDI/cmip6-cmor-tables/issues/237

**Comment by treerink** [comment]
PCMDI confirmed that indeed the proper "`m`" unit is missing, in fact the `olevhalf` coordinate has to be replaced with `depth_coord_half` in the `CMIP6_coordinate.json` file, so we need to wait their update. But from our side the problem seems then solved if we implement the changes for this new `depth_coord_half` coordinate as soon the update is there.

**Comment by goord** [comment]
As a pragmatic temporary solution, I now substitute 'meter' to any unit-less depth coordinate in the ocean tables, so we won't depend on new tables for releasing

**Comment by goord** [comment]
Fixed in pull request #405

**Comment by treerink** [comment]
Well as you said it is a temporary solution right? So don't know whether closing this issue is correct. Actually I want to check the latest cmor table status in a clean branch, because in the meanwhile we might have the complication that the tables might have been updated for data request version 01.00.30 (though usually there is a delay).

**Comment by treerink** [comment]
(Oh I see that I often accidentally referenced this issue in commit messages, they should have referenced #253 and the task-load-prefs branch).

**Comment by treerink** [comment]
Accidentally the cmor tables have been updated in the master as well, so I deleted the separate  `cmor-table-update` branch. The update is ok because it is still based on data request version 01.00.29 and PCMDI has added the `depth_coord_half` coordinate (including the unit) which we need to solve this problem. The cmor table update has removed our own unit modification in `olevhalf`, but as discussed [in PCMDI issue 237](https://github.com/PCMDI/cmip6-cmor-tables/issues/237) `depth_coord_half` should be used instead of `olevhalf`. 

However, at the `ece2cmor3` side it might need some change to correctly use `depth_coord_half` now.

**Comment by treerink** [comment]
A solution seems to be nearly released by PCMDI.

**Comment by treerink** [comment]
Tried it today with latest cmor tables, without succes, the required changes did not make it to the repository yet

**Comment by ufladrich** [comment]
Hi,
trying to cmorise three different experiments
- historical-EC-EARTH-Veg
- piControl-EC-EARTH-Veg
- ScenarioMIP-ssp126-EC-EARTH-Veg

and I encountered this error as well, as could be expected. However, I am a bit puzzled because I got it _only in the scenario case_, not the others. Is there any explanation for this? I can't see one from the `varlist.json` files.

**Comment by treerink** [comment]
Hi Uwe,

I am always testing all nemo output together, so it might be that the hist and piControl do not request variables which rely on this vertical coordinate, so then you miss the issue.

**Comment by treerink** [comment]
I have looked into the varlists and the file_def files you mentioned and they all include the variable `zhalfo` which causes the problem because of the `depth_coord` axis, so you should have the trouble in all three cases I would say? So unclear to me either?

**Comment by treerink** [comment]
In fb7d6b8 a temporary hack omits all `zhalfo` requests from the json data request files. As soon this issue is solved by PCMDI and the cmor tables are updated for that, the hack can be removed.

**Comment by treerink** [comment]
Checked once more the cmor table updates, unfortunately no further solving update. Therfore removing the  1.0 release label, we have to postpone this issue.

**Comment by treerink** [comment]
There seems merging progress here from PCMDI, a new cmor table update came just in. I will test if they indeed include the solution for this `zhalfo` vertical axis issue. However, I can already immediately see a complicated factor which I feared for already because of the proceeding time: the current cmor table is based on data request version `01.00.30`. It means now both dreq/drq and the latest cmor table version are based on data request `01.00.30`, the cmor lib also got an update today but I haven't figured out its data request version status, probably also matching `01.00.30` now.

**Comment by treerink** [comment]
I tested once more the cmorisation of `zhalfo` with the latest cmor table update, by running:
`````
ece2cmor ~/mount-point-lustre-3/ec-earth-3.3.0/branch-r6705-control-output-files/t009/output/nemo/001/ --exp t009 --nemo --conf ece2cmor3/resources/metadata-templates/cmip6-CMIP-piControl-metadata-template.json --vars ece2cmor3/resources/test-data-request/varlist-nemo-zhalfo.json --ececonf EC-EARTH-AOGCM --odir cmor-zhalfo --log
`````
I get the following errors:
`````
Traceback (most recent call last):
  File "/usr/people/reerink/anaconda2/envs/ece2cmor3/bin/ece2cmor", line 11, in <module>
    load_entry_point('ece2cmor3', 'console_scripts', 'ece2cmor')()
  File "/usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/ece2cmor.py", line 138, in main
    ece2cmorlib.perform_nemo_tasks(args.datadir, args.exp, refdate)
  File "/usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/ece2cmorlib.py", line 198, in perform_nemo_tasks
    nemo2cmor.execute(nemo_tasks)
  File "/usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/nemo2cmor.py", line 120, in execute
    execute_netcdf_task(dataset, task)
  File "/usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/nemo2cmor.py", line 167, in execute_netcdf_task
    varid = create_cmor_variable(task, dataset, axes)
  File "/usr/people/reerink/cmorize/ece2cmor3/ece2cmor3/nemo2cmor.py", line 229, in create_cmor_variable
    original_name=str(srcvar))
  File "/usr/people/reerink/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/cmor/pywrapper.py", line 546, in variable
    missing_value, tolerance, positive, original_name, history, comment)
_cmor.CMORError: Problem with 'cmor.variable'. Please check the logfile (if defined).
`````
and
`````
C Traceback:
! In function: cmor_variable
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: You defined variable 'zhalfo' (table Omon) with axis id 'depth_coord_half' which is not part of this variable according to your table, it says: ( time olevhalf latitude longitude )
!
!!!!!!!!!!!!!!!!!!!!!!!!!
`````

Up to here it goes fine:
`````
2019-04-19 11:43:12 INFO:ece2cmor3.taskloader: Created 2 ece2cmor tasks from input variable list.
2019-04-19 11:43:12 INFO:ece2cmor3.ece2cmorlib: Selected 2 NEMO tasks from 2 input tasks
2019-04-19 11:43:12 INFO:ece2cmor3.nemo2cmor: Looking up variables in files...
2019-04-19 11:43:12 ERROR:ece2cmor3.nemo2cmor: Variable zhalfo needed for zhalfo in table Oclim was not found in NEMO output files... skipping task
2019-04-19 11:43:12 INFO:ece2cmor3.nemo2cmor: Creating NEMO grids in CMOR...
2019-04-19 11:43:12 INFO:ece2cmor3.nemo2cmor: Executing 1 NEMO tasks...
2019-04-19 11:43:12 INFO:ece2cmor3.nemo2cmor: Cmorizing NEMO tasks...
2019-04-19 11:43:12 INFO:ece2cmor3.nemo2cmor: Start cmorization of zhalfo in table Omon
2019-04-19 11:43:12 INFO:ece2cmor3.nemo2cmor: Creating time axes for table Omon from data in /usr/people/reerink/mount-point-lustre-3/ec-earth-3.3.0/branch-r6705-control-output-files/t009/ou
tput/nemo/001/t009_1m_19900101_19901231_opa_grid_T_3D.nc...
2019-04-19 11:43:12 INFO:ece2cmor3.nemo2cmor: Creating time axis for table Omon using file /usr/people/reerink/mount-point-lustre-3/ec-earth-3.3.0/branch-r6705-control-output-files/t009/outp
ut/nemo/001/t009_1m_19900101_19901231_opa_grid_T_3D.nc...
2019-04-19 11:43:12 INFO:ece2cmor3.nemo2cmor: Creating depth axes for table Omon from data in /usr/people/reerink/mount-point-lustre-3/ec-earth-3.3.0/branch-r6705-control-output-files/t009/o
utput/nemo/001/t009_1m_19900101_19901231_opa_grid_T_3D.nc ...
2019-04-19 11:43:12 INFO:ece2cmor3.nemo2cmor: Creating depth axes for table Omon using file /usr/people/reerink/mount-point-lustre-3/ec-earth-3.3.0/branch-r6705-control-output-files/t009/out
put/nemo/001/t009_1m_19900101_19901231_opa_grid_T_3D.nc...
2019-04-19 11:43:12 INFO:ece2cmor3.nemo2cmor: Creating extra axes for table Omon from data in /usr/people/reerink/mount-point-lustre-3/ec-earth-3.3.0/branch-r6705-control-output-files/t009/o
utput/nemo/001/t009_1m_19900101_19901231_opa_grid_T_3D.nc ...
2019-04-19 11:43:12 INFO:ece2cmor3.nemo2cmor: Creating extra axes for table Omon using file /usr/people/reerink/mount-point-lustre-3/ec-earth-3.3.0/branch-r6705-control-output-files/t009/out
put/nemo/001/t009_1m_19900101_19901231_opa_grid_T_3D.nc...
`````

**Comment by treerink** [comment]
The PCMDI issue has been closed mentioning that they assume that the vertical axis issue is solved. I will try if `zhalfo` can be cmorised now. However as posted before, the update ships together with the `cmor table` update for the next data request version `01.00.30.` And I see already dimensional changes/updates in just the cmor table update. As we know the cmor table data request version and the `drq` version should be equal, also a `drq` update needs to be tested.

**Comment by treerink** [comment]
Just reporting: with the latest cmor tables (and the data request updated to version `01.00.30`) I was able to cmorise `zhalfo`  successfully with a local adjusted master, so this is not yet committed.

It seems that the data request update to version `01.00.30` is not giving too much issues so far. The cmor table update requires further testing due to other fixes.

**Comment by treerink** [comment]
In 6cbe795 `zhalfo` is again added to the json data request files with `genecec.` With the combined cmor table & data request update #463 & #464 `zhalfo` can be cmorised now, so this issue is finally solved.

Closing.

**Comment by oloapinivad** [comment]
Hi, I have just tried to use the last commit (did a fresh installation) and using the last version of the varlist (cmip6-data-request-varlist-CMIP-historical-EC-EARTH-AOGCM.json) 
However it crashes on `zhalfo` 

```
^[[1;31;47m!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: You defined variable 'zhalfo' (table Omon) with axis id 'depth_coord', the variable calls for a generic axis of type 'olevhalf' according to your table, the axis you are providing is of generic type 'olevel'
!
!!!!!!!!!!!!!!!!!!!!!!!!!^[[0m

````

My experiments were run with the previous version of the ctrl files, are those things related? 
Cheers,
Paolo

**Comment by treerink** [comment]
It looks like your cmor tables are for some reason not update? Though you should have updated them with a git pull, unless you have a previous updating action. Can you try to remove them and then a
`````
git submodule update --init --recursive
`````

No it does not depend on the control output files (when they are not too old, but I guess they are not).

**Comment by oloapinivad** [comment]
I did it again, but I still have the issue. 

I am a bit confused: the table installed is reading `"dimensions": "longitude latitude olevhalf time"`
This is the same reported here for `zhalfo` https://github.com/PCMDI/cmip6-cmor-tables/blob/d7f9eead12545f3daf1c6eaeb266433875f4cd3c/Tables/CMIP6_Omon.json

From the error it seems ece2cmor3 is providing the variable on olevel, does it make sense?

**Comment by oloapinivad** [comment]
Which is actually what I have in the data:

```
ncdump -h ch00_1m_18650101_18651231_opa_grid_T_3D.nc | grep zhalfo
	float zhalfo(time_counter, olevel, y, x) ;
		zhalfo:standard_name = "depth_below_geoid" ;
		zhalfo:long_name = "T-point depth" ;
		zhalfo:units = "m" ;
		zhalfo:online_operation = "average" ;
		zhalfo:interval_operation = "2700 s" ;
		zhalfo:interval_write = "1 month" ;
		zhalfo:cell_methods = "time: mean (interval: 2700 s)" ;
		zhalfo:cell_measures = "area: area" ;
		zhalfo:_FillValue = 1.e+20f ;
		zhalfo:missing_value = 1.e+20f ;
		zhalfo:coordinates = "time_centered nav_lat nav_lon" ;
```

**Comment by oloapinivad** [comment]
@treerink I am experiencing a strange behaviour.

If I run the the full varlist (i.e. `r6858/runtime/classic/ctrl/cmip6-output-control-files/CMIP/EC-EARTH-AOGCM/cmip6-experiment-CMIP-historical/cmip6-data-request-varlist-CMIP-historical-EC-EARTH-AOGCM.json`) I am experiencing the crash.

Conversely, when I run a short variable list with only `zhalfo` and a few other variables (as the one below), it works fine.
````
{
    "ifs": {
        "3hr": [
            "pr",
            "tas"
        ],
        "day": [
            "tasmin",
            "tasmax"
        ]
    },
    "lpjg": {},
    "nemo": {
        "3hr": [
            "tos"
        ],
        "Omon": [
            "zhalfo",
            "tos"
        ]
    },
    "tm5": {}
```

Does it make sense? Did you experience anything similar?

**Comment by oloapinivad** [comment]
I have a possible explanation: 

If you run with `zhalfo` only it works fine.
However, if you add any other Omon variable which are on the olevel grid as for example `bigthetao` something occurs in the code and the vertical levels (olevel vs. olevhalf) get mixed. This makes the code to crash. Any other has similar experience? 

Cheers,
Paolo

**Comment by oloapinivad** [comment]
Actually reverting the order of the variables (`zhalfo` before and `bigthetao` after) I can make the cmorization crash on the latter. May this depend on the fact this is output from r6827?

`````

C Traceback:
! In function: cmor_variable
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: You defined variable 'bigthetao' (table Omon) with axis id 'depth_coord_half', the variable calls for a generic axis of type 'olevel' according to your table, the axis you are providing is of generic type 'olevhalf'
!
!!!!!!!!!!!!!!!!!!!!!!!!!
`````

**Comment by pnolan22** [comment]
Just to add that I am also having the same problem with the zhalfo variable:

! Error: You defined variable 'zhalfo' (table Omon) with axis id 'depth_coord', the variable calls for a generic axis of type 'olevhalf' according to your table, the axis you are providing is of generic type 'olevel'

I used EC-Earth 3.3.1 (and the control output files of this version) and the latest master version of  ece2cmor3.

**Comment by treerink** [comment]
Indeed I can confirm that currently the cmorisation of `zhalfo`  works if one cmorises only `zhalfo` with for instance `resources/test-data-request/varlist-nemo-zhalfo.json`, but fails with a larger cmorisation task, i.e. if there other vars included. We have been looking into this, because this is a rather strange case. Probably  we kind of identified the problem, @goord is working on a solution.

**Comment by goord** [comment]
The problem is that the zhalfo variable depends on the netcdf dimension 'olevel'. In the multi-variable case, nemo2cmor tries to re-use the axis from some other 3D variable, which is not allowed by CMOR.

I will build in a hacky fix to prevent this, essentially forcing zhalfo to always have its own dedicated vertical axis.

**Comment by goord** [comment]
I pushed commit ca4b0105c5a3b07dffdf1baba95dd8ded989feac to the master branch which should resolve this problem . @treerink can you test once more?

**Comment by treerink** [comment]
Yes this works. So now `zhalfo` is also produced when cmorising the test-all-nemo-variables case.

So closing

**Comment by oloapinivad** [comment]
I can confirm it works fine now.
