### ISSUE TITLE
The drq2varlist.py script is broken

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#410]
Unfortunately `drq2varlist.py` was already broken at the time it has been merged into the master branch.  My guess is that something goes wrong in `match_variables`.

**Comment by goord** [comment]
Rev. dab0ec20f0f029f46fd71ad618f6c6c79aac7a62

**Comment by treerink** [comment]
Using `drq2varlist.py` with a (classic) json file is working now, e.g. (for nemo only):
`````
./drq2varlist.py --drq ../resources/test-data-request/varlist-nemo-all.json --ececonf EC-EARTH-AOGCM
`````
However with using `drq2varlist.py` with an xlsx like:
`````
./drq2varlist.py --drq cmip6-data-request/cmip6-data-request-m=CMIP-e=CMIP-t=1-p=1/cmvme_CMIP_piControl_1_1.xlsxv --ececonf EC-EARTH-AOGCM
`````
 still gives problems:
`````
2019-03-20 10:30:45 INFO:ece2cmor3.taskloader: Reading input variable list as json string...
Traceback (most recent call last):
  File "./drq2varlist.py", line 53, in <module>
    main()
  File "./drq2varlist.py", line 38, in main
    matches, omitted = taskloader.load_drq(args.drq, config=args.ececonf, check_prefs=True)
  File "/home/thomas/cmorize/ece2cmor3/ece2cmor3/taskloader.py", line 104, in load_drq
    requested_targets = read_drq(varlist)
  File "/home/thomas/cmorize/ece2cmor3/ece2cmor3/taskloader.py", line 215, in read_drq
    targetlist = load_targets_json(varlist, asfile=False)
  File "/home/thomas/cmorize/ece2cmor3/ece2cmor3/taskloader.py", line 275, in load_targets_json
    vardict = json.loads(vartext)
  File "/home/thomas/anaconda2/envs/ece2cmor3/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/home/thomas/anaconda2/envs/ece2cmor3/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/thomas/anaconda2/envs/ece2cmor3/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
`````

**Comment by goord** [comment]
Thomas this is an "xlsxv" file... what kind of format is that?

**Comment by treerink** [comment]
Sorry Gijs a typo, indeed the following does work:
`````
./drq2varlist.py --drq cmip6-data-request/cmip6-data-request-m\=CMIP-e\=CMIP-t\=1-p\=1/cmvme_CMIP_piControl_1_1.xlsx --ececonf EC-EARTH-AOGCM
`````
So closing again.
