### ISSUE TITLE
Cmorise Efx slthick

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#439]
In #143 `Efx slthick` is on the list to be implemented. As far I understand in `ifs2cmor.py` the function `create_soil_depth_axis` is defined in which these soil depths are hard coded. 

One thing is that this `Efx slthick` is not part of the ifspar.json, but as it does not have a grib code it probably does not need to be there? I just added a test varlist for `slthick`, anyway if I try to test it I get:
`````
Traceback (most recent call last):
  File "/lustre2/projects/model_testing/reerink/anaconda2/envs/ece2cmor3/bin/ece2cmor", line 11, in <module>
    load_entry_point('ece2cmor3==0.9.0', 'console_scripts', 'ece2cmor')()
  File "/lustre2/projects/model_testing/reerink/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-0.9.0-py2.7.egg/ece2cmor3/ece2cmor.py", line 118, in main
    check_duplicates=True)
  File "/lustre2/projects/model_testing/reerink/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-0.9.0-py2.7.egg/ece2cmor3/taskloader.py", line 74, in load_tasks
    return create_tasks(filtered_matches, get_models(active_components))
  File "/lustre2/projects/model_testing/reerink/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-0.9.0-py2.7.egg/ece2cmor3/taskloader.py", line 533, in create_tasks
    parmatch = [b for b in parblocks if matchvarpar(target, b)][0]
IndexError: list index out of range
`````

**Comment by treerink** [comment]
In e0dc90214e1c183291cf95482c43dfe283acf695 the `varlist-ifs-slthick.json` was added to test this one.

**Comment by goord** [comment]
Please test with the slthick branch.

**Comment by treerink** [comment]
Testing with:
`````
ece2cmor ~/mount-point-lustre-3/ec-earth-3.3.0/branch-r6705-control-output-files/t009/output/nemo/001/ --exp t009 --nemo --conf ece2cmor3/resources/metadata-templates/cmip6-CMIP-piControl-metadata-template.json --vars ece2cmor3/resources/test-data-request/varlist-ifs-slthick.json --ececonf EC-EARTH-AOGCM --odir cmor-slthick --log
`````

**Comment by treerink** [comment]
Error:
````
Traceback (most recent call last):
  File "/usr/people/reerink/anaconda2/envs/ece2cmor3/bin/ece2cmor", line 11, in <module>
    load_entry_point('ece2cmor3==0.9.8', 'console_scripts', 'ece2cmor')()
  File "/usr/people/reerink/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-0.9.8-py2.7.egg/ece2cmor3/ece2cmor.py", line 136, in main
    cdothreads=args.ncdo)
  File "/usr/people/reerink/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-0.9.8-py2.7.egg/ece2cmor3/ece2cmorlib.py", line 185, in perform_ifs_tasks
    ifs2cmor.execute(ifs_tasks, nthreads=taskthreads)
  File "/usr/people/reerink/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-0.9.8-py2.7.egg/ece2cmor3/ifs2cmor.py", line 181, in execute
    read_mask(task.target.variable, getattr(task, cmor_task.output_path_key))
`````

**Comment by treerink** [comment]
In the log: `Field missing in the first day of file: code 172.128, level type 1, level 0. Dismissing task land in table fx`:
````
2019-04-19 15:15:36 INFO:ece2cmor3.ifs2cmor: Validated 1 tasks for processing.
2019-04-19 15:15:36 INFO:ece2cmor3.ifs2cmor: Executing 1 IFS tasks...
2019-04-19 15:15:36 ERROR:ece2cmor3.grib_filter: Field missing in the first day of file: code 172.128, level type 1, level 0. Dismissing task land in table fx
2019-04-19 15:15:36 INFO:ece2cmor3.grib_filter: Filtering grib file /usr/people/reerink/mount-point-lustre-3/ec-earth-3.3.0/branch-r6705-control-output-files/t013/output/ifs/001/ICMGGt013+19
9001...
2019-04-19 15:15:36 INFO:ece2cmor3.grib_filter: Filtering grib file /usr/people/reerink/mount-point-lustre-3/ec-earth-3.3.0/branch-r6705-control-output-files/t013/output/ifs/001/ICMSHt013+19
9001...
2019-04-19 15:16:34 INFO:ece2cmor3.grib_filter: Filtering grib file /usr/people/reerink/mount-point-lustre-3/ec-earth-3.3.0/branch-r6705-control-output-files/t013/output/ifs/001/ICMGGt013+19
9002...
2019-04-19 15:17:15 INFO:ece2cmor3.grib_filter: Filtering grib file /usr/people/reerink/mount-point-lustre-3/ec-earth-3.3.0/branch-r6705-control-output-files/t013/output/ifs/001/ICMSHt013+19
9002...
2019-04-19 15:17:25 INFO:ece2cmor3.grib_filter: Filtering grib file /usr/people/reerink/mount-point-lustre-3/ec-earth-3.3.0/branch-r6705-control-output-files/t013/output/ifs/001/ICMGGt013+19
9003...
2019-04-19 15:18:22 INFO:ece2cmor3.grib_filter: Filtering grib file /usr/people/reerink/mount-point-lustre-3/ec-earth-3.3.0/branch-r6705-control-output-files/t013/output/ifs/001/ICMGGt013+19
9004...
2019-04-19 15:18:47 INFO:ece2cmor3.grib_filter: Filtering grib file /usr/people/reerink/mount-point-lustre-3/ec-earth-3.3.0/branch-r6705-control-output-files/t013/output/ifs/001/ICMSHt013+19
9003...
2019-04-19 15:19:17 INFO:ece2cmor3.grib_filter: Filtering grib file /usr/people/reerink/mount-point-lustre-3/ec-earth-3.3.0/branch-r6705-control-output-files/t013/output/ifs/001/ICMGGt013+19
9005...
2019-04-19 15:20:15 INFO:ece2cmor3.grib_filter: Filtering grib file /usr/people/reerink/mount-point-lustre-3/ec-earth-3.3.0/branch-r6705-control-output-files/t013/output/ifs/001/ICMGGt013+19
9006...
2019-04-19 15:20:31 INFO:ece2cmor3.grib_filter: Filtering grib file /usr/people/reerink/mount-point-lustre-3/ec-earth-3.3.0/branch-r6705-control-output-files/t013/output/ifs/001/ICMSHt013+19
9004...
2019-04-19 15:21:08 INFO:ece2cmor3.grib_filter: Filtering grib file /usr/people/reerink/mount-point-lustre-3/ec-earth-3.3.0/branch-r6705-control-output-files/t013/output/ifs/001/ICMGGt013+19
9007...
2019-04-19 15:22:05 INFO:ece2cmor3.grib_filter: Filtering grib file /usr/people/reerink/mount-point-lustre-3/ec-earth-3.3.0/branch-r6705-control-output-files/t013/output/ifs/001/ICMGGt013+19
9008...
2019-04-19 15:22:10 INFO:ece2cmor3.grib_filter: Filtering grib file /usr/people/reerink/mount-point-lustre-3/ec-earth-3.3.0/branch-r6705-control-output-files/t013/output/ifs/001/ICMSHt013+19
9005...
2019-04-19 15:23:01 INFO:ece2cmor3.grib_filter: Filtering grib file /usr/people/reerink/mount-point-lustre-3/ec-earth-3.3.0/branch-r6705-control-output-files/t013/output/ifs/001/ICMGGt013+19
9009...
2019-04-19 15:23:51 INFO:ece2cmor3.grib_filter: Filtering grib file /usr/people/reerink/mount-point-lustre-3/ec-earth-3.3.0/branch-r6705-control-output-files/t013/output/ifs/001/ICMSHt013+19
9006...
2019-04-19 15:23:58 INFO:ece2cmor3.grib_filter: Filtering grib file /usr/people/reerink/mount-point-lustre-3/ec-earth-3.3.0/branch-r6705-control-output-files/t013/output/ifs/001/ICMGGt013+19
9010...
2019-04-19 15:24:56 INFO:ece2cmor3.grib_filter: Filtering grib file /usr/people/reerink/mount-point-lustre-3/ec-earth-3.3.0/branch-r6705-control-output-files/t013/output/ifs/001/ICMGGt013+19
9011...
2019-04-19 15:25:24 INFO:ece2cmor3.grib_filter: Filtering grib file /usr/people/reerink/mount-point-lustre-3/ec-earth-3.3.0/branch-r6705-control-output-files/t013/output/ifs/001/ICMSHt013+19
9007...
2019-04-19 15:25:52 INFO:ece2cmor3.grib_filter: Filtering grib file /usr/people/reerink/mount-point-lustre-3/ec-earth-3.3.0/branch-r6705-control-output-files/t013/output/ifs/001/ICMGGt013+19
9012...
2019-04-19 15:26:56 INFO:ece2cmor3.grib_filter: Filtering grib file /usr/people/reerink/mount-point-lustre-3/ec-earth-3.3.0/branch-r6705-control-output-files/t013/output/ifs/001/ICMSHt013+19
9008...
2019-04-19 15:27:42 INFO:ece2cmor3.grib_filter: Filtering grib file /usr/people/reerink/mount-point-lustre-3/ec-earth-3.3.0/branch-r6705-control-output-files/t013/output/ifs/001/ICMSHt013+19
9009...
2019-04-19 15:28:25 INFO:ece2cmor3.grib_filter: Filtering grib file /usr/people/reerink/mount-point-lustre-3/ec-earth-3.3.0/branch-r6705-control-output-files/t013/output/ifs/001/ICMSHt013+19
9010...
2019-04-19 15:29:11 INFO:ece2cmor3.grib_filter: Filtering grib file /usr/people/reerink/mount-point-lustre-3/ec-earth-3.3.0/branch-r6705-control-output-files/t013/output/ifs/001/ICMSHt013+19
9011...
2019-04-19 15:29:54 INFO:ece2cmor3.grib_filter: Filtering grib file /usr/people/reerink/mount-point-lustre-3/ec-earth-3.3.0/branch-r6705-control-output-files/t013/output/ifs/001/ICMSHt013+19
9012...
````

**Comment by treerink** [comment]
With 769136784b8cffcc86c48a7a4fe7e55f1de808cf this issue is fixed and the cmorisation of `slthick` ended well.

**Comment by treerink** [comment]
The `slthick` branch is merged into the master.

Closing.

**Comment by treerink** [comment]
In b35652e `slthick` is activated by taking it off from the identified missing lists.

Issue solved.
