### ISSUE TITLE
Error in ifspar.json: multiple source found found for target sftgrf

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#482]
The error shows up with running `checkvars.py:`
`````
Traceback (most recent call last):
  File "./checkvars.py", line 193, in <module>
    main()
  File "./checkvars.py", line 155, in main
    matches, omitted_targets = taskloader.load_drq(args.drq, check_prefs=False)
  File "/home/thomas/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-1.1.0-py2.7.egg/ece2cmor3/taskloader.py", line 122, in load_drq
    matches = match_variables(targets, model_vars)
  File "/home/thomas/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-1.1.0-py2.7.egg/ece2cmor3/taskloader.py", line 488, in match_variables
    target.variable, target.table))
Exception: Invalid model parameter file /home/thomas/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-1.1.0-py2.7.egg/ece2cmor3/resources/ifspar.json: multiple source found found for target sftgrf in table Efx
`````
Indeed in ifspar.json we have right at the start:
`````
    {
        "source": "30.126",
        "target": "sftgrf"
    },
    {
        "source": "31.126",
        "target": "sncls"
    },
    {
        "source": "32.126",
        "target": "sftgif"
    },
    {
        "source": "33.126",
        "target": "sftgrf"
    },

`````

**Comment by treerink** [comment]
I think the error comes from the yellow (where the next column to the right is correct) column in the [shared doc for table 126 grib codes](https://docs.google.com/spreadsheets/d/17ipCYh48U0N0or8b0qG-_ALGmeD79wwK-s4W38r_YtM/edit#gid=1285118949), so it seems the second `33.126` can be removed from the `ifspar.json`.

**Comment by treerink** [comment]
Done
