### ISSUE TITLE
Broken NEMO cmorization following yr frequency update

### ISSUE THREAD

**Issue by oloapinivad** [EC-Earth/ece2cmor3#511]
Hi all,

I have just checked out the most recent commit (https://github.com/EC-Earth/ece2cmor3/commit/4890558ba7ad07666200713f24238ec391cea87a) following the merging of the yearly branch. 

IFS cmorizations are fine but I have crashes in the NEMO ones, again with `zhalfo` problem related to wrong coordinates. Anybody else has the same experience? 

That's the logfile:

`````
^[[2;31;47mC Traceback:
! In function: cmor_variable
! ^[[0m

^[[1;31;47m!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: You defined variable 'zhalfo' (table Omon) with axis id 'depth_coord_half' which is not part of this variable according to your table, it says: ( time olevhalf latt
itude longitude )
!
!!!!!!!!!!!!!!!!!!!!!!!!!^[[0m

Traceback (most recent call last):
  File "/perm/ms/it/ccpd/ecearth3/cmorization/ece2cmor3/ece2cmor3/ece2cmor.py", line 158, in <module>
    main()
  File "/perm/ms/it/ccpd/ecearth3/cmorization/ece2cmor3/ece2cmor3/ece2cmor.py", line 143, in main
    ece2cmorlib.perform_nemo_tasks(args.datadir, args.exp, refdate)
  File "/lus/snx11062/scratch/ms/it/ccpd/PRIMAVERA/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-1.2.0-py2.7.egg/ece2cmor3/ece2cmorlib.py", line 199, in pee
rform_nemo_tasks
    nemo2cmor.execute(nemo_tasks)
  File "/lus/snx11062/scratch/ms/it/ccpd/PRIMAVERA/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-1.2.0-py2.7.egg/ece2cmor3/nemo2cmor.py", line 113, in execc
ute
    execute_netcdf_task(dataset, task)
  File "/lus/snx11062/scratch/ms/it/ccpd/PRIMAVERA/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-1.2.0-py2.7.egg/ece2cmor3/nemo2cmor.py", line 160, in execc
ute_netcdf_task
    varid = create_cmor_variable(task, dataset, axes)
  File "/lus/snx11062/scratch/ms/it/ccpd/PRIMAVERA/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-1.2.0-py2.7.egg/ece2cmor3/nemo2cmor.py", line 221, in creaa
te_cmor_variable
    original_name=str(srcvar))
  File "/lus/snx11062/scratch/ms/it/ccpd/PRIMAVERA/anaconda2/envs/ece2cmor3/lib/python2.7/site-packages/cmor/pywrapper.py", line 546, in variable
    missing_value, tolerance, positive, original_name, history, comment)
_cmor.CMORError: Problem with 'cmor.variable'. Please check the logfile (if defined).
````

**Comment by treerink** [comment]
I am afraid with the merging of the yearly branch in 4890558ba7ad07666200713f24238ec391cea87a some old cmor tables have been committed by @goord to the master.

I am fixing this right now, with a new version, which is slightly newer than before.

**Comment by goord** [comment]
Ah shoot...

**Comment by treerink** [comment]
Problem is solved with the latest master version after 
```
git submodule update --init --recursive
```
from your ece2cmor root dir.

Closing.

**Comment by oloapinivad** [comment]
Thanks a lot NEMO is field! Unfortunately it seems not over, I have a problem with some IFS variables, opening a new issue soon!
