### ISSUE TITLE
No leap calendar for nemo only runs

### ISSUE THREAD

**Issue by aearamos** [EC-Earth/ece2cmor3#512]
Hi, following issue #467, here at BSC we're running NEMO-only and OMIP simulations and I got an error with the new cmorisation because of the "no leap" option in our calendar. Here's the error:

2019-07-08 13:40:01 INFO:ece2cmor3.nemo2cmor: Creating time axis for table Omon using file /gpfs/scratch/bsc32/bsc32044/t06d/19900101/fc00/runtime/output/nemo/002/t06d_1m_19900201_19900228_opa_grid_U_2D.nc...
Traceback (most recent call last):
  File "./ece2cmor.py", line 158, in <module>
    main()
  File "./ece2cmor.py", line 143, in main
    ece2cmorlib.perform_nemo_tasks(args.datadir, args.exp, refdate)
  File "/gpfs/scratch/bsc32/bsc32044/t06d/auto-ecearth3/ece2cmor/ece2cmor3/ece2cmorlib.py", line 199, in perform_nemo_tasks
    nemo2cmor.execute(nemo_tasks)
  File "/gpfs/scratch/bsc32/bsc32044/t06d/auto-ecearth3/ece2cmor/ece2cmor3/nemo2cmor.py", line 105, in execute
    create_time_axes(dataset, task_list, table)
  File "/gpfs/scratch/bsc32/bsc32044/t06d/auto-ecearth3/ece2cmor/ece2cmor3/nemo2cmor.py", line 297, in create_time_axes
    tstamps, tunits = cmor_utils.date2num(times, ref_time=ref_date_)
  File "/gpfs/scratch/bsc32/bsc32044/t06d/auto-ecearth3/ece2cmor/ece2cmor3/cmor_utils.py", line 65, in date2num
    return numpy.vectorize(shift_times)(times), ' '.join(["hours", "since", str(ref_time)])
  File "/apps/PYTHON/2.7.14/INTEL/lib/python2.7/site-packages/numpy/lib/function_base.py", line 2091, in __call__
    return self._vectorize_call(func=func, args=vargs)
  File "/apps/PYTHON/2.7.14/INTEL/lib/python2.7/site-packages/numpy/lib/function_base.py", line 2161, in _vectorize_call
    ufunc, otypes = self._get_ufunc_and_otypes(func=func, args=args)
  File "/apps/PYTHON/2.7.14/INTEL/lib/python2.7/site-packages/numpy/lib/function_base.py", line 2121, in _get_ufunc_and_otypes
    outputs = func(*inputs)
  File "/gpfs/scratch/bsc32/bsc32044/t06d/auto-ecearth3/ece2cmor/ece2cmor3/cmor_utils.py", line 63, in shift_times
    return (t - ref_time).total_seconds() / 3600.
  File "netcdftime/_netcdftime.pyx", line 1336, in netcdftime._netcdftime.datetime.__sub__ (netcdftime/_netcdftime.c:24214)
ValueError: cannot compute the time difference between dates with different calendars

Is there a way to include this option?

Thanks!

**Comment by goord** [comment]
Strange, because I thought at that stage we only had python datetime objects without calendar reference. However after some digging, from the netCDF4 API documentation:

> Note: The datetime instances returned are 'real' python datetime objects if calendar='proleptic_gregorian', or calendar='standard' or 'gregorian' and the date is after the breakpoint between the Julian and Gregorian calendars (1582-10-15). Otherwise, they are 'phony' datetime objects which support some but not all the methods of 'real' python datetime objects. The datetime instances do not contain a time-zone offset, even if the specified units contains one.

**Comment by goord** [comment]
Hi Arthur, I created the branch noleap-fix, could you test your output with it? If it works, you will have incorrect output because the cmor calendar attribute will be incorrect, but that's a problem I can fix later

**Comment by aearamos** [comment]
Hi Gijs, 
Apparently, the fix worked. The cmor calendar_attirbute is "proleptic_gregorian", as you said. Would it be just a matter of renaming it and adding the option of no leap calendar? 

Thank you very much.

**Comment by goord** [comment]
Hi Arthur, I will add an option to take the NEMO-produced calendar as the final output calendar of the cmorized data.

**Comment by treerink** [comment]
@goord it looks like this issue is nearly solved, the noleap-fix branch is not merged yet. Is it ready for merge? Or your latest post has to be addressed still?

**Comment by goord** [comment]
It's not ready yet, I have to adapt the CMOR calendar too, will do this asap

**Comment by goord** [comment]
Ok @aearamos and @treerink I inserted the calendar for no-leap nemo runs. It will produce the CMOR files also with that calendar.

**Comment by aearamos** [comment]
Hi @goord 
Should I test using trunk or the no-leap branch? Thanks!

**Comment by goord** [comment]
The no-leap branch

**Comment by aearamos** [comment]
Apparently, the changes are working and the name in the calendar is right. 

We can close the issue and I'll reopen in case I find something else.
