### ISSUE TITLE
Error when cmorising IFS with the last version

### ISSUE THREAD

**Issue by aearamos** [EC-Earth/ece2cmor3#571]
Hi, I have the following error when cmorising IFS:

2019-12-16 14:37:24 INFO:ece2cmor3.ece2cmorlib: Selected 101 IFS tasks from 101 input tasks
Traceback (most recent call last):
  File "./ece2cmor.py", line 157, in <module>
    main()
  File "./ece2cmor.py", line 141, in main
    cdothreads=args.ncdo)
  File "/gpfs/scratch/bsc32/bsc32436/a2ei/auto-ecearth3/ece2cmor/ece2cmor3/ece2cmorlib.py", line 182, in perform_ifs_tasks
    tempdir=tempdir, autofilter=auto_filter)):
  File "/gpfs/scratch/bsc32/bsc32436/a2ei/auto-ecearth3/ece2cmor/ece2cmor3/ifs2cmor.py", line 137, in initialize
    grib_filter.initialize(ifs_gridpoint_files_, ifs_spectral_files_, temp_dir_)
  File "/gpfs/scratch/bsc32/bsc32436/a2ei/auto-ecearth3/ece2cmor/ece2cmor3/grib_filter.py", line 42, in initialize
    grib_file.initialize()
  File "/gpfs/scratch/bsc32/bsc32436/a2ei/auto-ecearth3/ece2cmor/ece2cmor3/grib_file.py", line 29, in initialize
    orig_path = str(subprocess.check_output(["codes_info", "-d"]))
  File "/apps/PYTHON/2.7.14/INTEL/lib/python2.7/subprocess.py", line 212, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/apps/PYTHON/2.7.14/INTEL/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/apps/PYTHON/2.7.14/INTEL/lib/python2.7/subprocess.py", line 1025, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

I'm not sure what kind of file the grib_file and filter are looking for, so Im don't know if it's a problem in workflow or with ece2cmor. If I comment line 42 on grib_filter.py I'm able to cmorise IFS.

**Comment by goord** [comment]
Hi Arthur, this code is there to find the grib definition path of eccodes, which needs prepending with our own ec-earth grib table path. It's strange that it doesn't work on your system... what happens if you type
```
$ conda activate ece2cmor3
$ codes_info -d
```
If it doesn't find the codes_info script, something seems wrong with your eccodes installation...

**Comment by aearamos** [comment]
The thing's that I'm not using conda to run ece2cmor. In Autosubmit we load the modules and run without conda. Do I need this to cmorise all of the IFS variables?

**Comment by goord** [comment]
In principle you only need it for the PEXTRA variables. I can maybe define an environment variable to switch this off, but then you would need to prepend the ec-earth grib table directory yourself if you which to cmorize PEXTRA variables

**Comment by aearamos** [comment]
Apparently it was a module load problem. I'm testing it now and will close the issue once I know it's working. I forgot to load eccodes here.

**Comment by aearamos** [comment]
I'm closing the issue. It was a module problem. 
Thanks, Gijs.
