### ISSUE TITLE
Input files for remapping with CDO for LPJ-GUESS cannot be found

### ISSUE THREAD

**Issue by nierad** [EC-Earth/ece2cmor3#646]
Hi again, 

I just got a report from Wilhelm May about this error. If you install ece2cmor3 from scratch lpjg2cmor.py will not find the ingrid-files. 

```
Error in calling operator remapycon with:
>>> cdo -O remapycon,n128 -setgrid,//home/x_wilma/miniconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-1.4.0-py2.7.egg/ece2cmor3/resources/lpjg-grid-content/ingrid_T255_unstructured.txt /tmp/cmorize/LA05/lpjg/050/LPJGtemp.nc /tmp/cmorize/LA05/lpjg/050/cSoil_mon_2008.nc<<<
STDOUT:
 
STDERR:cdo(2) setgrid: Process started
cdo(2) setgrid (Abort): Open failed on //home/x_wilma/miniconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-1.4.0-py2.7.egg/ece2cmor3/resources/lpjg-grid-content/ingrid_T255_unstructured.txt!
 
Traceback (most recent call last):
  File "//home/x_wilma/miniconda2/envs/ece2cmor3/bin/ece2cmor", line 11, in <module>
    load_entry_point('ece2cmor3==1.4.0', 'console_scripts', 'ece2cmor')()
  File "//home/x_wilma/miniconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-1.4.0-py2.7.egg/ece2cmor3/ece2cmor.py", line 146, in main
    ece2cmorlib.perform_lpjg_tasks(args.datadir, args.tmpdir, args.exp, refdate)
  File "//home/x_wilma/miniconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-1.4.0-py2.7.egg/ece2cmor3/ece2cmorlib.py", line 213, in perform_lpjg_tasks
    lpjg2cmor.execute(lpjg_tasks)
  File "//home/x_wilma/miniconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-1.4.0-py2.7.egg/ece2cmor3/lpjg2cmor.py", line 233, in execute
    ncfile = create_lpjg_netcdf(freq, yearfile, outname, outdims)
  File "//home/x_wilma/miniconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-1.4.0-py2.7.egg/ece2cmor3/lpjg2cmor.py", line 514, in create_lpjg_netcdf
    output=ncfile)  # TODO: add remapping for possible other grids
  File "//home/x_wilma/miniconda2/envs/ece2cmor3/lib/python2.7/site-packages/cdo.py", line 377, in get
    raise CDOException(**retvals)
cdo.CDOException: (returncode:1) cdo(2) setgrid: Process started
cdo(2) setgrid (Abort): Open failed on //home/x_wilma/miniconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-1.4.0-py2.7.egg/ece2cmor3/resources/lpjg-grid-content/ingrid_T255_unstructured.txt! 
```

The same occured in issue #635

**Comment by treerink** [comment]
In the master branch?

Look in the folder:
 ece2cmor3/ece2cmor3/resources/lpjg-grid-content

There should be this:
```
create_cdo_ingrid_for_lpjgout.py*
ingrid_T159_unstructured.txt
ingrid_T255_unstructured.txt
lon-lat-lpjg-auxiliary-T159-grid.nc
lon-lat-lpjg-auxiliary-T255-grid.nc
```

Can you all check?

**Comment by nierad** [comment]
Hi Thomas,


Yes. I did this two days ago and Willi independently got to the same issue. He never used ece2cmor before and did everything according to the instructions on the git-website.

Cheers, Lars

________________________________

**Comment by nierad** [comment]
Just to add that the files (and actually the folder "lpjg-grid-content") are missing in:
`miniconda2/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-1.4.0-py2.7.egg/ece2cmor3/resources`

**Comment by etiennesky** [comment]
must be a problem in the miniconda installer...

**Comment by treerink** [comment]
Don't think this has anything to do with the miniconda version.

Can't think of any reason why the ingrid-files in the latest master branch in the ece2cmor3 repository can't be found, they are just there? You did the:
```
python setup.py install
```
in the ece2cmor root dir?

**Comment by treerink** [comment]
Problem not encountered. Please reopen if after correct install you still face trouble.
