### ISSUE TITLE
Cannot cmorize some COSP CALIPSO cloud fraction output

### ISSUE THREAD

**Issue by plesager** [EC-Earth/ece2cmor3#652]
Cmorizing a run with COSP output with release 1.5, I got these errors:

``` 
2020-08-27 11:22:14 ERROR:ece2cmor3.grib_filter: Field missing in the first day of file: code 40.126, level type 210, level 84000. Dismissing task cllcalipso in table CFmon
2020-08-27 11:22:14 ERROR:ece2cmor3.grib_filter: Field missing in the first day of file: code 41.126, level type 210, level 56000. Dismissing task clmcalipso in table CFmon
2020-08-27 11:22:14 ERROR:ece2cmor3.grib_filter: Field missing in the first day of file: code 42.126, level type 210, level 22000. Dismissing task clhcalipso in table CFmon
```
`ece2cmor3` does not complain about the four 43-46.126 requests, which are also COSP output. The problematic variables are `cl{l,m,h}`, the low/mid/high-level cloud fractions. The total cloud fraction (43.126 and 44.126) is not a problem.

**Comment by klauswyser** [comment]
Could it be that these fields are missing at the 1st timestep, i.e. in the ICMGG*000000 file?

**Comment by goord** [comment]
Can you check the initial state file? Does this happen for all legs or just the first?

**Comment by plesager** [comment]
Happening for all legs. Data are present in all files according to grib message headers:

```
cca-login4 /scratch/ms/nl/nm6/ECEARTH-RUNS/amip/output/ifs/001 
[5295] >>> grib_ls -x -P paramId -w typeOfLevel=surface ICMGGamip+000000 | grep "^126"
126040       1            ecmf         surface      0            19600101     0            fc           ~            grid_simple  reduced_gg  
126041       1            ecmf         surface      0            19600101     0            fc           ~            grid_simple  reduced_gg  
126042       1            ecmf         surface      0            19600101     0            fc           ~            grid_simple  reduced_gg  
126043       1            ecmf         surface      0            19600101     0            fc           ~            grid_simple  reduced_gg  
126044       1            ecmf         surface      0            19600101     0            fc           ~            grid_simple  reduced_gg  
126045       1            ecmf         surface      0            19600101     0            fc           ~            grid_simple  reduced_gg  
126046       1            ecmf         surface      0            19600101     0            fc           ~            grid_simple  reduced_gg  
126068       1            ecmf         surface      0            19600101     0            fc           ~            grid_simple  reduced_gg  
126069       1            ecmf         surface      0            19600101     0            fc           ~            grid_simple  reduced_gg  
126070       1            ecmf         surface      0            19600101     0            fc           ~            grid_simple  reduced_gg  
126071       1            ecmf         surface      0            19600101     0            fc           ~            grid_simple  reduced_gg  
126072       1            ecmf         surface      0            19600101     0            fc           ~            grid_simple  reduced_gg  
126073       1            ecmf         surface      0            19600101     0            fc           ~            grid_simple  reduced_gg  
126074       1            ecmf         surface      0            19600101     0            fc           ~            grid_simple  reduced_gg  
126075       1            ecmf         surface      0            19600101     0            fc           ~            grid_simple  reduced_gg  

cca-login4 /scratch/ms/nl/nm6/ECEARTH-RUNS/amip/output/ifs/001 
[5296] >>> cd ../019

cca-login4 /scratch/ms/nl/nm6/ECEARTH-RUNS/amip/output/ifs/019 
[5297] >>> grib_ls -x -P paramId -w typeOfLevel=surface,dataDate=19780101 ICMGGamip+197801 | grep "^12604"
126040       1            ecmf         surface      0            19780101     0            fc           ~            grid_simple  reduced_gg  
126041       1            ecmf         surface      0            19780101     0            fc           ~            grid_simple  reduced_gg  
126042       1            ecmf         surface      0            19780101     0            fc           ~            grid_simple  reduced_gg  
126043       1            ecmf         surface      0            19780101     0            fc           ~            grid_simple  reduced_gg  
126044       1            ecmf         surface      0            19780101     0            fc           ~            grid_simple  reduced_gg  
126045       1            ecmf         surface      0            19780101     0            fc           ~            grid_simple  reduced_gg  
126046       1            ecmf         surface      0            19780101     0            fc           ~            grid_simple  reduced_gg  
126040       1            ecmf         surface      0            19780101     0            fc           ~            grid_simple  reduced_gg  
126041       1            ecmf         surface      0            19780101     0            fc           ~            grid_simple  reduced_gg  
126042       1            ecmf         surface      0            19780101     0            fc           ~            grid_simple  reduced_gg  
126043       1            ecmf         surface      0            19780101     0            fc           ~            grid_simple  reduced_gg  
126044       1            ecmf         surface      0            19780101     0            fc           ~            grid_simple  reduced_gg  
126045       1            ecmf         surface      0            19780101     0            fc           ~            grid_simple  reduced_gg  
126046       1            ecmf         surface      0            19780101     0            fc           ~            grid_simple  reduced_gg  
126040       1            ecmf         surface      0            19780101     0            fc           ~            grid_simple  reduced_gg  
126041       1            ecmf         surface      0            19780101     0            fc           ~            grid_simple  reduced_gg  
126042       1            ecmf         surface      0            19780101     0            fc           ~            grid_simple  reduced_gg  
126043       1            ecmf         surface      0            19780101     0            fc           ~            grid_simple  reduced_gg  
126044       1            ecmf         surface      0            19780101     0            fc           ~            grid_simple  reduced_gg  
```

**Comment by goord** [comment]
Hi Philippe, I think it's the level type that's the problem here, the grib file says surface but ece2cmor3 is looking for a specific pressure level. I can correct this in the grib filter.

This is actually a common issue in ifs2cmor and I haven't found a systematic way to treat such mismatches or exceptions

**Comment by plesager** [comment]
Ok, I will wait for a fix then. I'll keep enough data alive on my scratch so we can test.

**Comment by goord** [comment]
I have pushed a fix to the cosp-filter-fix branch

**Comment by plesager** [comment]
Trying the new branch, something's broken. I got an encoding error:

```
ECCODES ERROR   :  Key "level": Trying to encode value of 84000 but the maximum allowable value is 65535 (number of bits=16)

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/scratch/ms/nl/nm6/miniconda2/envs/ece2cmor3/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/scratch/ms/nl/nm6/miniconda2/envs/ece2cmor3/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/perm/ms/nl/nm6/cmorize/ece2cmor3/ece2cmor3/grib_filter.py", line 526, in filter_grib_files
    proc_initial_month(date.month, grib_file.create_grib_file(fin), keys2files, grid, handles, once)
  File "/perm/ms/nl/nm6/cmorize/ece2cmor3/ece2cmor3/grib_filter.py", line 553, in proc_initial_month
    write_record(gribfile, key + (gridtype,), keys2files, handles=handles, once=once, setdate=None)
  File "/perm/ms/nl/nm6/cmorize/ece2cmor3/ece2cmor3/grib_filter.py", line 649, in write_record
    gribfile.set_field(grib_file.level_key, key[3])
  File "/perm/ms/nl/nm6/cmorize/ece2cmor3/ece2cmor3/grib_file.py", line 85, in set_field
    gribapi.grib_set(self.record, name, value)
  File "/scratch/ms/nl/nm6/miniconda2/envs/ece2cmor3/lib/python2.7/site-packages/gribapi/gribapi.py", line 88, in modified
    return _func_(**kw)
  File "/scratch/ms/nl/nm6/miniconda2/envs/ece2cmor3/lib/python2.7/site-packages/gribapi/gribapi.py", line 1717, in grib_set
    grib_set_long(msgid, key, value)
  File "/scratch/ms/nl/nm6/miniconda2/envs/ece2cmor3/lib/python2.7/site-packages/gribapi/gribapi.py", line 88, in modified
    return _func_(**kw)
  File "/scratch/ms/nl/nm6/miniconda2/envs/ece2cmor3/lib/python2.7/site-packages/gribapi/gribapi.py", line 822, in grib_set_long
    GRIB_CHECK(_internal.grib_c_set_long(msgid, key, value))
  File "/scratch/ms/nl/nm6/miniconda2/envs/ece2cmor3/lib/python2.7/site-packages/gribapi/gribapi.py", line 88, in modified
    return _func_(**kw)
  File "/scratch/ms/nl/nm6/miniconda2/envs/ece2cmor3/lib/python2.7/site-packages/gribapi/gribapi.py", line 136, in GRIB_CHECK
    errors.raise_grib_error(errid)
  File "/scratch/ms/nl/nm6/miniconda2/envs/ece2cmor3/lib/python2.7/site-packages/gribapi/errors.py", line 235, in raise_grib_error
    raise ERROR_MAP[errid](errid)
EncodingError: Encoding invalid                                                                                            
```

**Comment by goord** [comment]
Yes I should have seen that coming, annoying grib encoding of pressure levels. I think I fixed that, you can try once more...

**Comment by plesager** [comment]
Getting there... type error:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/scratch/ms/nl/nm6/miniconda2/envs/ece2cmor3/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/scratch/ms/nl/nm6/miniconda2/envs/ece2cmor3/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/perm/ms/nl/nm6/cmorize/ece2cmor3/ece2cmor3/grib_filter.py", line 526, in filter_grib_files
    proc_initial_month(date.month, grib_file.create_grib_file(fin), keys2files, grid, handles, once)
  File "/perm/ms/nl/nm6/cmorize/ece2cmor3/ece2cmor3/grib_filter.py", line 553, in proc_initial_month
    write_record(gribfile, key + (gridtype,), keys2files, handles=handles, once=once, setdate=None)
  File "/perm/ms/nl/nm6/cmorize/ece2cmor3/ece2cmor3/grib_filter.py", line 649, in write_record
    gribfile.set_field(grib_file.pressure_level_hPa_code, key[3]/100)
  File "/perm/ms/nl/nm6/cmorize/ece2cmor3/ece2cmor3/grib_file.py", line 85, in set_field
    gribapi.grib_set(self.record, name, value)
  File "/scratch/ms/nl/nm6/miniconda2/envs/ece2cmor3/lib/python2.7/site-packages/gribapi/gribapi.py", line 87, in modified
    "Parameter '%s' should be of type %s" % (name, " or ".join([t.__name__ for t in allowed_types]))
AssertionError: Parameter 'key' should be of type str
```

**Comment by goord** [comment]
Right another stupid mistake, that should be fixed now

**Comment by plesager** [comment]
It works!
