### ISSUE TITLE
An innocent OMIP error in the genecec log

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#660]
No `ppt` files are found in the `cmip6-output-control-files/OMIP/cmip6-experiment-OMIP-omip1/` directory. This is in agreement with the data request of OMIP in which the `ifs` part is empty:
```
cmip6-output-control-files/OMIP/cmip6-experiment-OMIP-omip1/cmip6-data-request-varlist-OMIP-omip1-EC-EARTH-CC.json
```
which is of course obvious because it is ocean only.

However `genecec` tries to run:
```
./drq2ppt.py --drq cmip6-data-request/cmip6-data-request-m=OMIP-e=omip1-t=1-p=1/cmvme_OMIP_omip1_1_1.xlsx
```
with an empty `ifs` list,  which gives an innocent crash (everything continues fine). But it might be better that this case is catched in order to prevent confusing errors in the `genecec` log file.

The error part is:
```
Running drq2ppt.py with:
 ./drq2ppt.py --drq cmip6-data-request/cmip6-data-request-m=RFMIP-e=rad-irf-t=1-p=1/cmvme_RFMIP_rad-irf_1_1.xlsx

Traceback (most recent call last):
  File "./drq2ppt.py", line 327, in <module>
    main()
  File "./drq2ppt.py", line 320, in main
    write_ppt_files(ece2cmorlib.tasks)
  File "./drq2ppt.py", line 113, in write_ppt_files
    min_freq = max(freqgroups.keys())
ValueError: max() arg is an empty sequence
mv: cannot stat 'ppt0000000000': No such file or directory
mv: cannot stat 'pptdddddd*': No such file or directory
```

**Comment by treerink** [comment]
Calling drq2ppt is now omitted for OMIP experiments, which prevents the reported error in the genecec-log files.

Done

**Comment by treerink** [comment]
When `drq2ppt` is skipped a message is sent by `genecec` with a reference to this issue.
