### ISSUE TITLE
Testing the python-3-klaus branch

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#737]
I have freshly installed `ece2cmor3-py3` on my ubuntu laptop by using `mamba` (this uses `python3.10`) which is thus based on the `python-3-klaus` branch.

In an active environment I am able to run very basic stuff like: `cdo -V` (v2.05), `ece2cmor3 -h`, `drq -h`.

The first thing I try is to run `genecec` (I had ported `genecec` earlier to python3 and this was at least at that time working). In the new branch probably some more changes have been made, so let's test.

I get the following error now:
```
Traceback (most recent call last):
  File "/home/thomas/cmorize/ece2cmor3/ece2cmor3/scripts/./genecec.py", line 27, in <module>
    dq = dreq.loadDreq()
  File "/home/thomas/mamba/envs/ece2cmor3-py3/lib/python3.10/site-packages/dreqPy/dreq.py", line 1020, in __init__
    self.c = config( thisdoc=dreqXML, configdoc=configdoc, useShelve=useShelve,strings=strings,manifest=manifest,configOnly=configOnly,lxml=lxml)
  File "/home/thomas/mamba/envs/ece2cmor3-py3/lib/python3.10/site-packages/dreqPy/dreq.py", line 581, in __init__
    self.__read__(d, c)
  File "/home/thomas/mamba/envs/ece2cmor3-py3/lib/python3.10/site-packages/dreqPy/dreq.py", line 657, in __read__
    self.parent_map = dict((c, p) for p in root.getiterator() for c in p)
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getiterator'
```
I have not dived into it yet, first asking @zklaus if you have immediately an idea about this. Maybe [here](https://stackoverflow.com/questions/64264563/attributeerror-elementtree-object-has-no-attribute-getiterator-when-trying) the direction of the answer can be found.

**Comment by zklaus** [comment]
Let's take this in the PR.
