### ISSUE TITLE
os error in lpjg2cmor.py

### ISSUE THREAD

**Issue by noije** [EC-Earth/ece2cmor3#769]
I get the following error after a fresh install of ece2cmor on ECMWF HPC2020. Could be a mamba/conda version issue, as I am using the most recent versions of those (mamba version 1.4.4 and conda 23.1.0).
```
ece2cmor -V
Traceback (most recent call last):
  File "/etc/ecmwf/nfs/dh2_perm_b/nks/mamba/envs/ece2cmor3/bin/ece2cmor", line 5, in <module>
    from ece2cmor3.ece2cmor import main
  File "/etc/ecmwf/nfs/dh2_perm_b/nks/mamba/envs/ece2cmor3/lib/python3.11/site-packages/ece2cmor3/ece2cmor.py", line 11, in <module>
    from ece2cmor3 import ece2cmorlib, taskloader, components, __version__, cmor_target, cmor_utils
  File "/etc/ecmwf/nfs/dh2_perm_b/nks/mamba/envs/ece2cmor3/lib/python3.11/site-packages/ece2cmor3/ece2cmorlib.py", line 12, in <module>
    from ece2cmor3 import __version__, cmor_target, cmor_task, nemo2cmor, ifs2cmor, lpjg2cmor, tm52cmor, postproc, \
  File "/etc/ecmwf/nfs/dh2_perm_b/nks/mamba/envs/ece2cmor3/lib/python3.11/site-packages/ece2cmor3/lpjg2cmor.py", line 39, in <module>
    gridfile_ = os.path.join(os.path.dirname(__file__), "resources/lpjg-grid-content", "ingrid_T255_unstructured.txt")
                ^^
NameError: name 'os' is not defined
```

**Comment by treerink** [comment]
Surprisingly the missing:
```
import os
```
in the file `lpjg2cmor.py` did not raise earlier this error. Anyway fixing this BUG seems to solve the problem, where at the HPC2020 with the latest mamba/conda install even an _ece2cmor -V_ was not working.
