### ISSUE TITLE
LPJG cmorisation fails after porting to python3

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#771]
The LPJG cmorisation was not tested for the `v2.x.x` releases. We are now facing issues which most likely are related to the transition to the python3 based version. 

The issues related to the mismatch between the bytes or string type, seem to be solved (locally, branch has to be pushed still).

Current status (locally) is that though all LPJG cmorised files are produced, they appear all to contain only fields with zeros. Thus needs further debugging.

Note that in emergency case (when immediate use of LPJG cmorisation is required), one could use the `ece2cmor3` `v1.9.1` version for cmorising LPJG data, because for the LPJG part no recent fixes have been applied in the latest `v2.x.x` versions.

**Comment by treerink** [comment]
First crash error for ece2cmor3's lpjg component:
```
Traceback (most recent call last):
  File "/etc/ecmwf/nfs/dh2_perm_b/nktr/mamba/envs/ece2cmor3/bin/ece2cmor", line 33, in <module>
    sys.exit(load_entry_point('ece2cmor3', 'console_scripts', 'ece2cmor')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/etc/ecmwf/nfs/dh1_home_b/nktr/cmorize/ece2cmor3/ece2cmor3/ece2cmor.py", line 146, in main
    ece2cmorlib.perform_lpjg_tasks(args.datadir, args.tmpdir, args.exp, refdate)
  File "/etc/ecmwf/nfs/dh1_home_b/nktr/cmorize/ece2cmor3/ece2cmor3/ece2cmorlib.py", line 244, in perform_lpjg_tasks
    lpjg2cmor.execute(lpjg_tasks)
  File "/etc/ecmwf/nfs/dh1_home_b/nktr/cmorize/ece2cmor3/ece2cmor3/lpjg2cmor.py", line 209, in execute
    if not check_time_resolution(lpjgfile, freq):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/etc/ecmwf/nfs/dh1_home_b/nktr/cmorize/ece2cmor3/ece2cmor3/lpjg2cmor.py", line 318, in check_time_resolution
    elif freq.startswith("yr"):
         ^^^^^^^^^^^^^^^^^^^^^
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
```
A next one:
```
Traceback (most recent call last):
  File "/etc/ecmwf/nfs/dh2_perm_b/nktr/mamba/envs/ece2cmor3/bin/ece2cmor", line 33, in <module>
    sys.exit(load_entry_point('ece2cmor3', 'console_scripts', 'ece2cmor')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/etc/ecmwf/nfs/dh1_home_b/nktr/cmorize/ece2cmor3/ece2cmor3/ece2cmor.py", line 146, in main
    ece2cmorlib.perform_lpjg_tasks(args.datadir, args.tmpdir, args.exp, refdate)
  File "/etc/ecmwf/nfs/dh1_home_b/nktr/cmorize/ece2cmor3/ece2cmor3/ece2cmorlib.py", line 244, in perform_lpjg_tasks
    lpjg2cmor.execute(lpjg_tasks)
  File "/etc/ecmwf/nfs/dh1_home_b/nktr/cmorize/ece2cmor3/ece2cmor3/lpjg2cmor.py", line 234, in execute
    ncfile = create_lpjg_netcdf(freq, yearfile, outname, outdims)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/etc/ecmwf/nfs/dh1_home_b/nktr/cmorize/ece2cmor3/ece2cmor3/lpjg2cmor.py", line 484, in create_lpjg_netcdf
    df_out, dimensions = coords(df_list[l], root, meta)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/etc/ecmwf/nfs/dh1_home_b/nktr/cmorize/ece2cmor3/ece2cmor3/lpjg2cmor.py", line 117, in coords
    df.index.set_levels([run_lons, run_lats], inplace=True)
TypeError: MultiIndex.set_levels() got an unexpected keyword argument 'inplace'
```
These errors seem to be covered by the adjustments made in 29d5942, currently in the `771-lpjg-python3-porting` branch.

Though both variables (`Eyr cVeg` & `Emon cSoil`) from the `resources/miscellaneous-data-requests/test-data-request/varlist-minimal-test.json` request are cmorised, they contain only zero's so far.

**Comment by treerink** [comment]
2532a5e solves the largest remaining issue: the zeros and land are now replaced by the data (thanks @nierad ).

Remaining issue is that the missing values are still zero

**Comment by nierad** [comment]
> Remaining issue is that the missing values are still zero

0976e6f solves the missing "missing-values" issue.

**Comment by treerink** [comment]
Thanks @nierad for helping out with the zeros issue.

Issue solved. So also for LPJG cmorisation the latest python3 master can be used now.
