### ISSUE TITLE
Extra non-cmor TM5 output for downscaling

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#775]
The request here is an additional list of 77 non-cmor TM5 variables for downscaling within the FOCI project.

**Comment by treerink** [comment]
In 8ec8d2d `add-aerchem-list-for-foci.sh` script added, only the `long_name`s and `standard_name` s have to be added for all new variables in this script in the if-blocks.

**Comment by treerink** [comment]
Status of the script: it has been inspected thoroughly on content. The new json has been validated. But the cmorisation test on the ECMWF platform could not be done due to its down time.

**Comment by treerink** [comment]
The table patch is ready. The json files are fine.

However, the `tm5` component of ece2cmor encounters an error with this new inserted `AER6hrPt` table:
```
Traceback (most recent call last):
  File "/etc/ecmwf/nfs/dh2_perm_b/nktr/mamba/envs/ece2cmor3/bin/ece2cmor", line 33, in <module>
    sys.exit(load_entry_point('ece2cmor3', 'console_scripts', 'ece2cmor')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/etc/ecmwf/nfs/dh1_home_b/nktr/cmorize/ece2cmor3/ece2cmor3/ece2cmor.py", line 148, in main
    ece2cmorlib.perform_tm5_tasks(args.datadir, args.tmpdir, args.exp, refdate)
  File "/etc/ecmwf/nfs/dh1_home_b/nktr/cmorize/ece2cmor3/ece2cmor3/ece2cmorlib.py", line 256, in perform_tm5_tasks
    tm52cmor.execute(tm5_tasks)
  File "/etc/ecmwf/nfs/dh1_home_b/nktr/cmorize/ece2cmor3/ece2cmor3/tm52cmor.py", line 301, in execute
    create_depth_axes(task)
  File "/etc/ecmwf/nfs/dh1_home_b/nktr/cmorize/ece2cmor3/ece2cmor3/tm52cmor.py", line 743, in create_depth_axes
    axisid, psid = create_hybrid_level_axis(task)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/etc/ecmwf/nfs/dh1_home_b/nktr/cmorize/ece2cmor3/ece2cmor3/tm52cmor.py", line 798, in create_hybrid_level_axis
    axes=[getattr(task, 'lat'), getattr(task, 'lon'), getattr(task, "time_axis")]
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'cmor_task' object has no attribute 'time_axis'

```

**Comment by treerink** [comment]
The FOCI output-control-files are created and committed to the `r9728-foci-output` branch in the ECE repository, see also [ECE portal issue 1306-8](https://dev.ec-earth.org/issues/1306#note-8).
