### ISSUE TITLE
cmorization of latest LPJG output fails

### ISSUE THREAD

**Issue by etiennesky** [EC-Earth/ece2cmor3#777]
I am using ece2cmor1.8.1 with python2.7 on output from the optimesm branch and I get this error, is it different from the one you get with latest ece2cmor and python3?  @treerink @nierad 

```
2023-12-18 22:22:36 INFO:ece2cmor3.lpjg2cmor: Processing file /ec/res4/scratch/c3et/spesiccf/c3et/a6re/18500101/fc0/runtime/output/lpjg/001/mrsll_monthly.out
2023-12-18 22:22:39 INFO:ece2cmor3.lpjg2cmor: Creating lpjg netcdf file for variable mrsll for year 1850
2023-12-18 22:22:57 INFO:ece2cmor3.lpjg2cmor: Creating depth axis using file /ec/res4/scratch/c3et/spesiccf/c3et/a6re/18500101/fc0/runtime/output/lpjg/001/mrsll_monthly.out...
Traceback (most recent call last):
  File "./ece2cmor.py", line 156, in <module>
    main()
  File "./ece2cmor.py", line 145, in main
    ece2cmorlib.perform_lpjg_tasks(args.datadir, args.tmpdir, args.exp, refdate)
  File "/ec/res4/scratch/c3et/spesiccf/c3et/a6re/auto-ecearth3/ece2cmor/ece2cmor3/ece2cmorlib.py", line 223, in perform_lpjg_tasks
    lpjg2cmor.execute(lpjg_tasks)
  File "/ec/res4/scratch/c3et/spesiccf/c3et/a6re/auto-ecearth3/ece2cmor/ece2cmor3/lpjg2cmor.py", line 275, in execute
    create_sdepth_axis(task, lpjgfile, freq)
  File "/ec/res4/scratch/c3et/spesiccf/c3et/a6re/auto-ecearth3/ece2cmor/ece2cmor3/lpjg2cmor.py", line 825, in create_sdepth_axis
    sdepthvals = np.array([float(d) for d in depths])
ValueError: could not convert string to float: Depth0.1
```

**Comment by nierad** [comment]
Hi Etienne, 

It seems the line headers have been changed in the output recently. I'll come up with a fix very soon.
