### ISSUE TITLE
IFS cmorisation: list index out of range with cmor_utils.py

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#783]
The IFS ece2cmor3 is suffering at least since november from the following:
```
  File "/nfs/home/users/reerink/cmorize/ece2cmor3/ece2cmor3/cmor_utils.py", line 188, in read_time_stamps
    times = command.showtimestamp(input=path)[0].split()
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

I wonder whether this is connected to an April 10 commit 7c9c033 "Moved all IFS output finding to ifs2cmor.py, fixed backup directory issues"?

This affected the `test-all` tests, but also other cmorisation experiments (e.g. FOCI). In the `test-all` case I observed that really nearly everything was produced, but just a few files not sometimes only one of two years. When I repeated the cmorisation without changing anything there were missing not exactly the same ones, in that sense the result was unstable.

Typically the full error log looks like:
```
"""
Traceback (most recent call last):
  File "/lustre3/projects/CMIP6/reerink/mamba/envs/ece2cmor3/lib/python3.11/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/lustre3/projects/CMIP6/reerink/mamba/envs/ece2cmor3/lib/python3.11/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
           ^^^^^^^^^^^^^^^^
  File "/nfs/home/users/reerink/cmorize/ece2cmor3/ece2cmor3/ifs2cmor.py", line 348, in cmor_worker
    execute_netcdf_task(task)
  File "/nfs/home/users/reerink/cmorize/ece2cmor3/ece2cmor3/ifs2cmor.py", line 689, in execute_netcdf_task
    time_stamps = cmor_utils.read_time_stamps(filepath)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nfs/home/users/reerink/cmorize/ece2cmor3/ece2cmor3/cmor_utils.py", line 188, in read_time_stamps
    times = command.showtimestamp(input=path)[0].split()
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/lustre3/projects/CMIP6/reerink/mamba/envs/ece2cmor3/bin/ece2cmor", line 33, in <module>
    sys.exit(load_entry_point('ece2cmor3', 'console_scripts', 'ece2cmor')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nfs/home/users/reerink/cmorize/ece2cmor3/ece2cmor3/ece2cmor.py", line 137, in main
    ece2cmorlib.perform_ifs_tasks(args.datadir, args.exp,
  File "/nfs/home/users/reerink/cmorize/ece2cmor3/ece2cmor3/ece2cmorlib.py", line 219, in perform_ifs_tasks
    ifs2cmor.execute(ifs_tasks, nthreads=taskthreads)
  File "/nfs/home/users/reerink/cmorize/ece2cmor3/ece2cmor3/ifs2cmor.py", line 305, in execute
    pool.map(cmor_worker, proctasks)
  File "/lustre3/projects/CMIP6/reerink/mamba/envs/ece2cmor3/lib/python3.11/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre3/projects/CMIP6/reerink/mamba/envs/ece2cmor3/lib/python3.11/multiprocessing/pool.py", line 774, in get
    raise self._value
IndexError: list index out of range
```

**Comment by treerink** [comment]
Two examples of differences in the total produced cmorised variable lists:

```
diff /lustre3/projects/CMIP6/reerink/cmorised-results/test-all-branch-r9881-control-output-files/t002/v001/logs//produced-varlist.txt     /lustre3/projects/CMIP6/reerink/cmorised-results/test-all-trunk/t004/v001/logs//produced-varlist.txt
19a20
> LImon/tsIs:			tsIs_LImon_EC-Earth3_piControl_r1i1p1f1_gr_199001-199012.nc
445a447
> CFday/rsdscs:			rsdscs_CFday_EC-Earth3_piControl_r1i1p1f1_gr_19910101-19911231.nc
448a451
> CFday/rldscs:			rldscs_CFday_EC-Earth3_piControl_r1i1p1f1_gr_19900101-19901231.nc
739a743
> fx/sftlf:			sftlf_fx_EC-Earth3_piControl_r1i1p1f1_gr.nc
740a745
> fx/areacella:			areacella_fx_EC-Earth3_piControl_r1i1p1f1_gr.nc
901a907
> Amon/prsn:			prsn_Amon_EC-Earth3_piControl_r1i1p1f1_gr_199001-199012.nc
```

```
diff /lustre3/projects/CMIP6/reerink/cmorised-results/test-all-branch-r9881-control-output-files/t003/v001/logs//produced-varlist.txt     /lustre3/projects/CMIP6/reerink/cmorised-results/test-all-trunk/t004/v001/logs//produced-varlist.txt
18a19,20
> LImon/tsIs:			tsIs_LImon_EC-Earth3_piControl_r1i1p1f1_gr_199101-199112.nc
> LImon/tsIs:			tsIs_LImon_EC-Earth3_piControl_r1i1p1f1_gr_199001-199012.nc
23a26
> LImon/tsnIs:			tsnIs_LImon_EC-Earth3_piControl_r1i1p1f1_gr_199001-199012.nc
166a170
> 3hr/mrro:			mrro_3hr_EC-Earth3_piControl_r1i1p1f1_gr_199101010130-199112312230.nc
442a447,448
> CFday/rsdscs:			rsdscs_CFday_EC-Earth3_piControl_r1i1p1f1_gr_19910101-19911231.nc
> CFday/rsdscs:			rsdscs_CFday_EC-Earth3_piControl_r1i1p1f1_gr_19900101-19901231.nc
444a451,452
> CFday/rldscs:			rldscs_CFday_EC-Earth3_piControl_r1i1p1f1_gr_19900101-19901231.nc
> CFday/rldscs:			rldscs_CFday_EC-Earth3_piControl_r1i1p1f1_gr_19910101-19911231.nc
734a743
> fx/sftlf:			sftlf_fx_EC-Earth3_piControl_r1i1p1f1_gr.nc
735a745
> fx/areacella:			areacella_fx_EC-Earth3_piControl_r1i1p1f1_gr.nc
895a906
> Amon/prsn:			prsn_Amon_EC-Earth3_piControl_r1i1p1f1_gr_199101-199112.nc
904a916
> Amon/ps:			ps_Amon_EC-Earth3_piControl_r1i1p1f1_gr_199001-199012.nc
```

**Comment by goord** [comment]
Hi @treerink! So the issue is always triggered on the test-all request? It's probably not so easy anymore for me to reproduce...

**Comment by treerink** [comment]
This issue seems related to two `fx` variables:
```
fx areacella
fx sftlf
```
What probably happens that these are usually cmorised rather at the end of the IFS job, but as soon it crashes the other tasks stop and therefore depending on how the parallelized jobs have proceeded, a few of 'the last' different variables miss in the final output.

This at least seems the case in smaller tests. I am now running the `test-all` test minus these two variables for confirmation.

**Comment by treerink** [comment]
Indeed the full `test-all` test minus `fx areacella` & `fx sftlf` succeed without problem delivering all the remaining variables (and including `fx orog`, the latter never raised a problem). No irregular behaviour, all data for both legs is produced (so this means that the cause of the troubles for [ECE portal issue 1278-9](https://dev.ec-earth.org/issues/1278#note-9) are detected here.

**Comment by treerink** [comment]
ee9fb6e solves this issue. 

The `test-all` tests directly after the `ece2cmor3` `v2.1.0` did still deliver this variables with the mamba - python `3.11.0`  combination at that time. However with the current mamba - python `3.11.4` with the same `v2.1.0` which upgrade was just a few commits after that release, this issue is present. The reason is due to a different interpretation of an empty (time slice) list by cdo-py after going to a newer python version.

Thanks @goord for a joint BUG-sprint on this.
