### ISSUE TITLE
crash with ifs cmorisation of optimesm request

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#815]
A crash is encountered during `ifs` cmorisation. The current case concerns the cmorisation of the latest optimesm request (using the corresponding non-cmip6-cmor table injections.

```
Traceback (most recent call last):
  File "/lustre3/projects/CMIP6/reerink/mamba/envs/ece2cmor3/bin/ece2cmor", line 33, in <module>
    sys.exit(load_entry_point('ece2cmor3', 'console_scripts', 'ece2cmor')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nfs/home/users/reerink/cmorize/ece2cmor3/ece2cmor3/ece2cmor.py", line 137, in main
    ece2cmorlib.perform_ifs_tasks(args.datadir, args.exp,
  File "/nfs/home/users/reerink/cmorize/ece2cmor3/ece2cmor3/ece2cmorlib.py", line 231, in perform_ifs_tasks
    ifs2cmor.execute(ifs_tasks, nthreads=taskthreads)
  File "/nfs/home/users/reerink/cmorize/ece2cmor3/ece2cmor3/ifs2cmor.py", line 305, in execute
    pool.map(cmor_worker, proctasks)
  File "/lustre3/projects/CMIP6/reerink/mamba/envs/ece2cmor3/lib/python3.11/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre3/projects/CMIP6/reerink/mamba/envs/ece2cmor3/lib/python3.11/multiprocessing/pool.py", line 774, in get
    raise self._value
multiprocessing.pool.MaybeEncodingError: Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x7f1dbb9dc9d0>'. Reason: 'PicklingError("Can't pickle <class '_cmor.CMORError'>: import of
 module '_cmor' failed")'
```

**Comment by treerink** [comment]
See also [ECE portal post 1312-17 ](https://dev.ec-earth.org/issues/1312#note-177) and [ECE portal post 1312-189](https://dev.ec-earth.org/issues/1312#note-189).

**Comment by treerink** [comment]
Without the HTESSELday & HTESSELmon variables the IFS cmorisation of the optimesm request encounters no crash or error. So it's just a matter of fixing the cmorisation of the added HTESSEL variables.

**Comment by treerink** [comment]
Apart from the non well defined `type` in various of these new HTESSEL* table definitions for these new variables, the famous error of using  an underscore in a added cmor variable name causes the error (underscores are not allowed in CMOR variable names) in the two variables names:
`lai_lv`
`lai_hv`
so this needs to be adjusted.

The `typec3pft` in the table definition for the variable `c3PftFrac` (which is used as template for the HTESSEL variables) will for now be replaced by the existing `typeveg` type. A new type can be used later, if preferred.

**Comment by treerink** [comment]
All issues solved, fields look reasonable.
